---
sidebar: sidebar 
permalink: concept_lic_cp_operation.html 
keywords: license, licensing, Capacity Pools, operation details 
summary: Capacity Poolsライセンス モデルは、Capacity Tiersモデルとは異なります。各ノードに個別のストレージ容量を割り当てるのではなく、ストレージ容量はプールに割り当てられ、複数のノード間で共有されます。Capacity Poolsモデルをサポートするために、追加のコンポーネントとプロセスが作成されました。 
---
= ONTAP Select Capacity Poolsライセンス モデルの運用の詳細
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Capacity Poolsライセンス モデルは、Capacity Tiersモデルとは異なります。各ノードに個別のストレージ容量を割り当てるのではなく、ストレージ容量はプールに割り当てられ、複数のノード間で共有されます。Capacity Poolsモデルをサポートするために、追加のコンポーネントとプロセスが作成されました。



== ライセンス マネージャ

ライセンス マネージャは、Deploy 管理ユーティリティの各インスタンス内で独立したプロセスとして実行されます。LM が提供する機能には以下のようなものがあります：

* 容量プールライセンスのシリアル番号に基づいて、各ノードに固有の20桁のシリアル番号を生成します
* ONTAP Select ノードからのリクエストに基づいて、共有容量プールから容量のリースを作成します
* Deploy ユーザー インターフェイスを通じてプール使用状況情報をレポートします




== リース契約の特徴

容量プールライセンスを使用するノードのすべてのデータ アグリゲートに割り当てられたストレージには、関連付けられたリースが必要です。ノードがストレージのリースを要求し、容量が利用可能な場合、ライセンス マネージャはリースで応答します。各リースには、次の明示的または暗黙的な属性があります：

* ライセンス マネージャ
+
すべてのONTAP Selectノードは1つのLicense Managerインスタンスに関連付けられています

* Capacity Pool
+
すべての ONTAP Select ノードは 1 つのキャパシティ プールに関連付けられています

* ストレージ割り当て
+
リースでは特定の容量値が割り当てられます

* 有効期限日時
+
リースの期間は、ユーザー設定に応じて 1 時間から 7 日間になります。





== ライセンス ロック ID

License Managerの各インスタンス、および対応する各Deployユーティリティ インスタンスは、一意の128-bitの番号で識別されます。この番号は、9桁のCapacity Poolライセンス シリアル番号と組み合わされ、プールを特定のLicense Managerインスタンス（実質的にはDeployインスタンス）にロックします。NetApp License File（NLF）を生成する手順の一環として、NetApp Support Siteで両方の値を提供する必要があります。

Deploy インスタンスのライセンス ロック ID は、Web ユーザ インターフェイスを使用して次の方法で確認できます。

* スタートガイド ページ
+
Deploy に初めてサインインすると、このページが表示されます。ページ右上のドロップダウンボックスを開き、*Getting Started* を選択してこのページを表示することもできます。LLID は「ライセンスの追加」セクションに表示されます。

* ページ上部の*管理*タブを選択し、*システムとAutoSupport*を選択します。




== 基本的なリース操作

ONTAP Selectノードは、データ アグリゲートが作成、拡張、または変更されるたびに、有効な容量リースを検索または要求する必要があります。以前の要求で取得した有効なリースを使用することも、必要に応じて新しいリースを要求することもできます。ONTAP Selectノードは、容量プールリースを検索するために、以下の手順を実行します：

. ノードに既存のリースが存在する場合、以下のすべての条件が満たされている限り、そのリースが使用されます：
+
** リースの有効期限が切れていません
** アグリゲートのストレージ要求がリース容量を超えていない


. 既存のリースが見つからない場合、ノードはライセンス マネージャに新しいリースを要求します。




== ストレージ容量を容量プールに戻す

ストレージ容量は必要に応じて容量プールから割り当てられ、新しいリクエストが発生するたびに、プール内の利用可能なストレージ容量が減少する可能性があります。ストレージ容量は、以下のようないくつかの状況でプールに戻されます：

* データ アグリゲートのリースの有効期限が切れ、ノードによって更新されない
* データ アグリゲートが削除されました



NOTE: ONTAP Select仮想マシンが削除された場合、アクティブなリースは期限が切れるまで有効なままです。この場合、容量はプールに戻されます。
