---
sidebar: sidebar 
permalink: concept_lic_cp_restrictions.html 
keywords: license, licensing, Capacity Pools, restrictions 
summary: キャパシティプールライセンス モデルを使用する際に適用される制限事項を以下に示します。 
---
= ONTAP Select Capacity Pools ライセンスの導入制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
キャパシティプールライセンス モデルを使用する際に適用される制限事項を以下に示します。

.クラスタごとに一貫したライセンス モデル
単一の ONTAP Select クラスタ内のすべてのノードは、容量階層または容量プールのいずれかの同じライセンス モデルを使用する必要があります。単一のクラスタ内のノードに対して、異なるライセンスタイプを混在させることはできません。

.クラスター内のすべてのノードは同じLicense Managerインスタンスを使用します
ONTAP SelectクラスタのCapacity Poolライセンスを使用するすべてのノードで、同じLicense Managerインスタンスを使用する必要があります。各Deployインスタンス内にLicense Managerインスタンスが1つあるため、この制限は、同じDeployインスタンスでクラスタ内のすべてのノードを管理する必要があるという既存の要件を言い換えたものです。

.ノードごとに 1 つの容量プール
各ノードは、1つの容量プールからのみストレージをリースできます。ノードは2つ以上のプールを使用することはできません。

.HA ペア内のノードに同じプールを使用
単一のHAペアを構成する両方のノードは、同じ容量プールからストレージをリースする必要があります。ただし、同じクラスター内の異なるHAペアは、同じライセンスマネージャーによって管理される異なるプールからストレージをリースすることができます。

.ストレージ ライセンスの有効期間
NetAppからストレージライセンスを取得する際には、ライセンス期間を選択する必要があります。たとえば、ライセンスの有効期間は1年間です。

.データ アグリゲート リース期間
ONTAP Selectノードがデータ アグリゲートのストレージリースを要求すると、License Managerは、Capacity Poolの構成に基づいて、特定の期間のリースを提供します。各プールのリース期間は、1時間から7日間の間で設定できます。デフォルトのリース期間は24時間です。

.Deployに割り当てられた静的IPアドレス
Capacity Pools ライセンスを使用する場合は、Deploy 管理ユーティリティに静的 IP アドレスを割り当てる必要があります。
