---
sidebar: sidebar 
permalink: concept_lic_platforms.html 
keywords: license, licensing, platform license offerings, license offerings, standard, premium, premium xl 
summary: ONTAP Select の容量階層または容量プールのライセンスは、3 つのプラットフォーム容量レベルのいずれかで購入できます。これらのライセンス オファリングによって、ONTAP Select をデプロイするホストの機能が決まります。 
---
= ONTAP Select のプラットフォーム ライセンスの提供内容について学ぶ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 容量ティアまたは容量プールライセンスは、標準、プレミアム、またはプレミアム XL レベルで購入できます。これらのライセンス オファリングによって、ONTAP Select をデプロイするホストの機能が決まります。



== プラットフォーム ライセンスの提供内容

特定のライセンスの提供内容によって、ハイパーバイザー ホストの機能が次の 2 つの領域で決まります：

* インスタンス タイプ（CPU、メモリ）
* その他の機能


ライセンスの種類は、標準版からプレミアム版XLまで、機能の面で昇順に並んでいます。一般的に、選択したライセンスオプションによって、そのレベルとそれより下位のすべてのレベルの機能が利用可能になります。例えば、プレミアムレベルでは、プレミアムと標準版の両方の機能を提供します。

以下の表は、標準ライセンス、プレミアムライセンス、およびプレミアム XL ライセンスの機能を比較したものです。

[cols="25,25,25,25,25"]
|===
2+| ライセンスは以下をサポートします... | Standard | Premium | プレミアムXL 


2+| インスタンス タイプ | 小規模のみ | 小型または中型 | 小、中、大 


.2+| ハードディスク ドライブ（HDD）は... | ハードウェアRAID構成 | はい | はい | はい 


| vNAS 構成 | はい | はい | はい 


.3+| ソリッドステートドライブ（SSD）を | ハードウェアRAID構成 | × | はい | はい 


| ソフトウェアRAID構成 | × | はい | はい 


| vNAS 構成 | はい | はい | はい 


.3+| NVMe ドライブは... | ハードウェアRAID構成 | × | × | はい 


| ソフトウェアRAID構成 | × | × | はい 


| vNAS 構成 | はい | はい | はい 


2+| MetroCluster SDS | × | はい | はい 
|===

NOTE: カーネルベース仮想マシン（KVM）は、大規模インスタンス タイプをサポートしていません。



== プラットフォーム ライセンス製品のハードウェア サポートを比較

標準、プレミアム、プレミアム XL ライセンス オファリングは、幅広いハードウェアとソフトウェアをサポートします。ハードウェアとソフトウェアのバージョンに関する最新情報については、link:https://mysupport.netapp.com/matrix/["Interoperability Matrix Tool"^]を参照してください。

[role="tabbed-block"]
====
.コア項目
--
[cols="5"30"]
|===


2+| コアアイテムタイプ 3+| 説明 


2+| ホストプロトコル 3+| NFS、SMB/CIFS、iSCSI、およびTCP経由のNVMe 


2+| 導入オプション 3+| シングルノード 2ノードクラスタ（HAペア） 4、6、8、10、または12ノードクラスタ 


2+| サポートされる容量（ノードあたり） 3+| 最大400TBの生データ（ESXiおよびKVM） 
|===
--
.ハードウェア
--
[cols="5"30"]
|===


2+| ハードウェアタイプ 3+| 説明 


2+| インスタンスのサイズ | 小規模 | 中 | 大規模 


2+| CPUファミリー | Intel Xeon E5-26xx v3 (Haswell) 以降 | Intel Xeon E5-26xx v3 (Haswell) 以降 | Intel Xeon E5-26xx v3 (Haswell) 以降 


2+| ONTAP Select CPU / メモリ | 仮想CPU（vCPU）4基 / RAM 16GB | 8 vCPU / 64GB RAM | 16個の仮想CPU / 128GBのRAM 


2+| ホストCPU/メモリの最小要件^1^ | 6コア / 24GBのRAM | 10コア / 72GBのRAM | 18コア / 136GBのRAM 


2+| ネットワーク（ノードあたり） 3+| 単一ノードクラスタの場合は最低2つの1GbEポート 2ノードクラスタ（HAペア）の場合は最低4つの1GbEポート 4、6、8、10、または12ノードクラスタの場合は最低2つの10GbEポート 
|===
^1^ ハイパーバイザーに2つのコアと8GBのRAMを想定しています。

--
.ストレージ タイプ
--
以下の表は、指定されたストレージに必要な最小限のライセンスの種類を示しています。 

[cols="5"30"]
|===


2+| ストレージ タイプ 3+| 説明 


2+| ライセンス タイプ | Standard | Premium | プレミアムXL 


2+| インスタンスのサイズ | 小規模 | 小型および中型 | 小、中、大 


2+| ハードウェアRAIDコントローラを備えたローカルDAS | 8～60ドライブ | 8～60ドライブ | 8～60ドライブ 


2+| HDD（SAS、NL-SAS、SATA） | 該当なし | 4～60ドライブ | 4～60ドライブ 


2+| SSD（SAS） | 該当なし | 4～60台のドライブ（SSDのみ） | 4～60台のドライブ（SSDのみ） 


2+| ソフトウェアRAID搭載のローカルDAS | 該当なし | 該当する | 4～14台のドライブ（NVMeのみ） 


2+| 外部アレイ^1^ 3+| 外部アレイ上にホストされているデータストアは、FC、FCoE、iSCSI、およびNFSを介して接続されます（NFSはKVMではサポートされていません）。これらのデータストアは、高い可用性と耐障害性を提供します。 
|===
^1^ 外部アレイプロトコルのサポートは、ネットワークストレージ接続を反映しています。

--
.ソフトウェア
--
[cols="5"30"]
|===


2+| ソフトウェアの種類 3+| 説明 


2+| ハイパーバイザーのサポート（VMware） 3+| VMware vSphere 9.0 VMware vSphere 8.0GA およびアップデート 1 ～ 3 VMware vSphere 7.0GA およびアップデート 1 ～ 3C 


2+| ハイパーバイザーのサポート（KVM）  a| 
Red Hat Enterprise Linux 64-bit (KVM) 10.1、10.0、9.7、9.6、9.5、9.4、9.3、9.2、9.1、9.0、8.8、8.7、および 8.6

Rocky Linux (KVM) 10.1、10.0、9.7、9.6、9.5、9.4、9.3、9.2、9.1、9.0、8.9、8.8、8.7、8.6



2+| 管理ソフトウェア 3+| NetApp Active IQ Unified Manager管理スイートONTAP Select Deploy Utility SnapCenter（オプション） 
|===
--
====
.次の手順
link:concept_lic_workflow.html["ONTAP Selectライセンスの購入について"]
