---
sidebar: sidebar 
permalink: concept_api_operation.html 
keywords: rest api, deploy rest api, rest, operation, basic operation 
summary: RESTは共通の技術とベストプラクティスを確立するものの、各APIの詳細は設計上の選択によって異なる場合があります。APIを使用する前に、ONTAP Select Deploy APIの詳細と動作特性を把握しておく必要があります。 
---
= ONTAP Select Deploy APIの基本的な運用特性
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
RESTは共通の技術とベストプラクティスを確立するものの、各APIの詳細は設計上の選択によって異なる場合があります。APIを使用する前に、ONTAP Select Deploy APIの詳細と動作特性を把握しておく必要があります。



== ハイパーバイザー ホストと ONTAP Select ノード

_ハイパーバイザー ホスト_は、ONTAP Select仮想マシンをホストするコア ハードウェア プラットフォームです。ONTAP Select仮想マシンがハイパーバイザー ホスト上に導入されてアクティブになると、その仮想マシンは_ONTAP Selectノード_とみなされます。Deploy REST APIのバージョン3では、ホスト オブジェクトとノード オブジェクトは別個のものです。これにより、1対多の関係が可能になり、1つ以上のONTAP Selectノードを同じハイパーバイザー ホスト上で実行できます。



== オブジェクトID

各リソースインスタンスまたはオブジェクトは、作成時に一意の識別子が割り当てられます。これらの識別子は、ONTAP Select Deployの特定のインスタンス内でグローバルに一意です。新しいオブジェクトインスタンスを作成するAPI呼び出しを発行すると、関連付けられたID値がHTTPレスポンスの `location`ヘッダーで呼び出し元に返されます。識別子を抽出して、リソースインスタンスを参照する際の以降の呼び出しで使用できます。


NOTE: オブジェクト識別子の内容と内部構造は変更になることがあります。識別子を使用するのは、該当するAPI呼び出しで関連付けられているオブジェクトを参照するために必要な場合だけにしてください。



== リクエスト識別子

成功したAPIリクエストにはすべて、一意の識別子が割り当てられます。識別子は、関連するHTTPレスポンスの `request-id`ヘッダーで返されます。リクエスト識別子を使用すると、特定の単一のAPIリクエスト・レスポンス取引における一連の活動をまとめて参照できます。例えば、リクエストIDに基づいて、トランザクションに関するすべてのイベントメッセージを取得できます。



== 同期呼び出しと非同期呼び出し

サーバーがクライアントから受信したHTTPリクエストを処理する主な方法は2つあります。

* 同期型：サーバーはリクエストを即座に実行し、ステータスコード200、201、または204で応答します。
* 非同期：サーバーはリクエストを受け入れ、ステータスコード202で応答します。これは、サーバーがクライアントからのリクエストを受け入れ、リクエストを完了するためのバックグラウンドタスクを開始したことを示しています。最終的な成功または失敗はすぐには判明せず、追加のAPI呼び出しによって判定する必要があります。




== 長時間実行されるジョブの完了を確認する

一般的に、完了までに時間がかかる可能性のある操作は、サーバー側のバックグラウンドタスクを使用して非同期的に処理されます。Deploy REST APIでは、すべてのバックグラウンドタスクは、タスクを追跡し、現在の状態などの情報を提供するJobオブジェクトによってアンカーされます。バックグラウンドタスクが作成されると、一意の識別子を含むJobオブジェクトがHTTPレスポンスで返されます。

Jobオブジェクトを直接照会することで、関連するAPI呼び出しの成否を判断できます。詳細については、「Jobオブジェクトを使用した非同期処理」を参照してください。

Job オブジェクトを使用する以外にも、リクエストの成功または失敗を判断する方法はいくつかあります。

* イベントメッセージ 元のレスポンスで返されたリクエストIDを使用すると、特定のAPI呼び出しに関連付けられたすべてのイベントメッセージを取得できます。イベントメッセージには通常、成功または失敗を示す情報が含まれており、エラー状態のデバッグにも役立ちます。
* リソースの状態またはステータス 一部のリソースは、状態またはステータス値を保持しており、これを照会することでリクエストの成功または失敗を間接的に判断できます。




== セキュリティ

Deploy API は、以下のセキュリティ技術を使用しています：

* トランスポート層セキュリティ Deployサーバーとクライアント間のネットワーク上で送信されるすべてのトラフィックは、TLSによって暗号化されます。暗号化されていないチャネル上でHTTPプロトコルを使用することはサポートされていません。TLSバージョン1.2をサポートしています。
* HTTP認証　すべてのAPIトランザクションには基本認証が使用されます。ユーザー名とパスワードをbase64文字列で含むHTTPヘッダーが、すべてのリクエストに追加されます。

