---
sidebar: sidebar 
permalink: concept_api_rest.html 
keywords: rest api, deploy rest api, rest, architecture, resources, state, uri, http, json 
summary: Representational State Transfer（REST）は、分散型Webアプリケーションを作成するためのスタイルです。WebサービスAPIの設計に適用すると、サーバーベースのリソースを公開し、その状態を管理するための一連のテクノロジとベストプラクティスが確立されます。主流のプロトコルと標準を使用して、ONTAP Selectクラスタの導入と管理のための柔軟な基盤を提供します。 
---
= ONTAP Select クラスタを導入および管理するための REST Web サービス基盤
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Representational State Transfer（REST）は、分散型Webアプリケーションを作成するためのスタイルです。WebサービスAPIの設計に適用すると、サーバーベースのリソースを公開し、その状態を管理するための一連のテクノロジとベストプラクティスが確立されます。主流のプロトコルと標準を使用して、ONTAP Selectクラスタの導入と管理のための柔軟な基盤を提供します。



== アーキテクチャと従来の制約

RESTは、2000年にUC Irvineで Roy Fielding が博士論文 https://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm["学位論文"]の中で正式に提唱しました。これは、一連の制約を通じてアーキテクチャスタイルを定義するもので、これらの制約が集合的にWebベースのアプリケーションと基盤となるプロトコルを改善します。これらの制約により、ステートレス通信プロトコルを使用するクライアント/サーバーアーキテクチャに基づくRESTful Webサービスアプリケーションが確立されます。



== リソースと状態の表示

リソースはWebベース システムの基本コンポーネントです。REST Webサービス アプリケーションを作成する場合、設計の早い段階で次の作業を行います。

* システムまたはサーバーベースのリソースの識別 すべてのシステムはリソースを使用し、維持します。リソースとは、ファイル、ビジネス取引、プロセス、または管理エンティティなどを指します。REST Webサービスに基づいたアプリケーションを設計する際の最初のタスクの1つは、リソースを特定することです。
* リソースの状態と関連する状態操作の定義 リソースは常に有限個の状態のいずれかにあります。状態、および状態変化に影響を与えるために使用される関連操作は、明確に定義されなければなりません。


クライアントとサーバー間でメッセージが交換され、一般的なCRUD（作成、読み取り、更新、削除）モデルに従ってリソースの状態にアクセスしたり変更したりします。



== URIエンドポイント

すべてのRESTリソースは、明確に定義されたアドレス指定方式を使用して定義、提供される必要があります。リソースが置かれているエンドポイントは、Uniform Resource Identifier（URI）で識別されます。URIは、ネットワークの各リソースに一意の名前を作成するための一般的なフレームワークです。Uniform Resource Locator（URL）は、リソースを識別してアクセスするためにWebサービスで使用されるURIの一種です。リソースは、通常、ファイル ディレクトリに似た階層構造で公開されます。



== HTTPメッセージ

ハイパーテキスト転送プロトコル（HTTP）は、Webサービスクライアントとサーバーがリソースに関するリクエストメッセージとレスポンスメッセージを交換するために使用するプロトコルです。Webサービスアプリケーションの設計の一環として、HTTP動詞（GETやPOSTなど）はリソースとそれに対応する状態管理アクションにマッピングされます。

HTTPはステートレスです。したがって、一連の関連するリクエストとレスポンスを1つのトランザクションに関連付けるには、リクエスト/レスポンスのデータフローとともに伝送されるHTTPヘッダーに追加情報を含める必要があります。



== JSONの形式

クライアントとサーバー間で情報を構造化して転送する方法はいくつかありますが、最も一般的なオプション（Deploy REST APIで使用されるもの）はJavaScript Object Notation（JSON）です。JSONは、単純なデータ構造をプレーンテキストで表現するための業界標準であり、リソースを記述する状態情報の転送に使用されます。
