---
sidebar: sidebar 
permalink: concept_stor_eff_support.html 
keywords: ontap select, storage efficiency support 
summary: ONTAP Selectは、FASおよびAFFアレイに搭載されているストレージ効率化オプションと同様のストレージ効率化オプションを提供します。 
---
= ONTAP Select ストレージ効率のサポート
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Selectは、FASおよびAFFアレイに搭載されているストレージ効率化オプションと同様のストレージ効率化オプションを提供します。

オールフラッシュVSANまたは汎用フラッシュアレイを使用したONTAP Select仮想NAS（vNAS）の導入では、SSD以外の直接接続ストレージ（DAS）を使用したONTAP Selectのベストプラクティスに従う必要があります。

SSDドライブを搭載したDASストレージとプレミアムライセンスがあれば、新規インストール時にAFFのようなパーソナリティが自動的に有効になります。

AFFのようなパーソナリティを持つため、インストール時に以下のインラインSE機能が自動的に有効になります：

* インラインゼロパターン検出
* ボリュームインライン重複排除
* ボリュームのバックグラウンド重複排除
* 適応型インライン圧縮
* インライン データ コンパクション
* アグリゲート インライン重複排除
* アグリゲートのバックグラウンド重複排除


ONTAP Selectがデフォルトのストレージ効率化ポリシーをすべて有効にしていることを確認するには、新しく作成したボリュームで次のコマンドを実行します：

[listing]
----
<system name>::> set diag
Warning: These diagnostic commands are for use by NetApp personnel only.
Do you want to continue? {y|n}: y
twonode95IP15::*> sis config
Vserver:                                SVM1
Volume:                                 _export1_NFS_volume
Schedule                                -
Policy:                                 auto
Compression:                            true
Inline Compression:                     true
Compression Type:                       adaptive
Application IO Si                       8K
Compression Algorithm:                  lzopro
Inline Dedupe:                          true
Data Compaction:                        true
Cross Volume Inline Deduplication:      true
Cross Volume Background Deduplication:  true
----

NOTE: ONTAP Select 9.6以降からのアップグレードでは、プレミアムライセンス付きのDAS SSDストレージにONTAP Selectをインストールする必要があります。さらに、ONTAP Deployを使用した初回クラスタインストール時に*ストレージ効率を有効にする*チェックボックスをオンにする必要があります。事前条件が満たされていない場合にONTAPアップグレード後にAFFライクパーソナリティを有効にするには、ブート引数を手動で作成し、ノードを再起動する必要があります。詳細については、テクニカルサポートにお問い合わせください。

.ONTAP Selectストレージ効率の構成
以下の表は、メディアの種類とソフトウェアライセンスに応じて、利用可能なさまざまなストレージ効率化オプション、デフォルトで有効になっているオプション、デフォルトでは有効になっていないが推奨されるオプションをまとめたものです。

[cols="4"]
|===
| ONTAP Selectの機能 | DAS SSD（premium または premium XL^1^） | DAS HDD（全ライセンス） | vNAS（全ライセンス） 


| インラインゼロ検出 | はい（デフォルト） | はい、ボリュームごとにユーザーが有効化できます | はい、ボリュームごとにユーザーが有効化できます 


| ボリュームインライン重複排除 | はい（デフォルト） | 使用不可 | サポート対象外 


| 32Kインライン圧縮（セカンダリ圧縮） | はい。ユーザーがボリュームごとに有効化できます。 | はい、ボリュームごとにユーザーが有効化できます | サポート対象外 


| 8Kインライン圧縮（アダプティブ圧縮） | はい（デフォルト） | はい、ユーザーがボリュームごとに有効化します | サポート対象外 


| バックグラウンド圧縮 | サポート対象外 | はい、ユーザーがボリュームごとに有効化します | はい、ボリュームごとにユーザーが有効化できます 


| 圧縮スキャナー | はい | はい | はい、ボリュームごとにユーザーが有効化できます 


| インライン データ コンパクション | はい（デフォルト） | はい、ユーザーがボリュームごとに有効化します | サポート対象外 


| コンパクションスキャナー | はい | はい | サポート対象外 


| アグリゲート インライン重複排除 | はい（デフォルト） | 該当なし | サポート対象外 


| ボリュームのバックグラウンド重複排除 | はい（デフォルト） | はい、ユーザーがボリュームごとに有効化します | はい、ボリュームごとにユーザーが有効化できます 


| アグリゲートのバックグラウンド重複排除 | はい（デフォルト） | 該当なし | サポート対象外 
|===
[small]#^1^ONTAP Select 9.6では、新しいライセンス（premium XL）と新しいVMサイズ（large）がサポートされています。ただし、largeのVMは、ソフトウェアRAIDを使用するDAS構成でのみサポートされます。ハードウェアRAIDおよびvNAS構成は、9.6リリースのlargeのONTAP Select VMではサポートされていません。#

.DAS SSD構成のアップグレード動作に関する注意事項
ONTAP Select 9.6以降にアップグレードした後、既存のボリュームのStorage Efficiency値を確認する前に、 `system node upgrade-revert show`コマンドでアップグレードが完了したことを示すまで待ちます。

ONTAP Select 9.6以降にアップグレードされたシステムでは、既存のアグリゲートまたは新規に作成されたアグリゲート上に作成された新しいボリュームは、新規デプロイメント上に作成されたボリュームと同じ動作をします。ONTAP Selectコードアップグレードを経た既存のボリュームは、新規作成されたボリュームとほぼ同じストレージ効率ポリシーを持ちますが、いくつかの違いがあります：

シナリオ1:: アップグレード前にボリュームでストレージ効率化ポリシーが有効になっていなかった場合：
+
--
*  `space guarantee = volume`を使用するボリュームでは、インラインデータ圧縮、アグリゲートインライン重複排除、およびアグリゲートバックグラウンド重複排除が有効になっていません。これらのオプションはアップグレード後に有効にできます。
*  `space guarantee = none`を使用するボリュームでは、バックグラウンド圧縮が有効になっていません。このオプションはアップグレード後に有効にできます。
* アップグレード後、既存ボリュームのストレージ効率化ポリシーは auto に設定されます。


--
シナリオ2:: アップグレード前にボリュームでストレージ効率化機能が既に有効になっている場合：
+
--
*  `space guarantee = volume`を使用するボリュームは、アップグレード後も変化はありません。
*  `space guarantee = none`を持つボリュームは、アグリゲートバックグラウンド重複排除が有効になっています。
*  `storage policy inline-only`を持つボリュームのポリシーは自動に設定されています。
* ユーザー定義のストレージ効率ポリシーを持つボリュームのポリシーは変更されません。ただし、 `space guarantee = none`を持つボリュームは例外です。これらのボリュームでは、アグリゲートのバックグラウンド重複排除が有効になっています。


--

