---
sidebar: sidebar 
permalink: concept_nw_concepts_chars.html 
keywords: ontap select, networking concepts, cluster characteristics 
summary: まず、ONTAP Select環境に適用される一般的なネットワークの概念を理解してください。次に、シングルノードクラスタとマルチノードクラスタで利用可能な具体的な特性とオプションについて詳しく見ていきましょう。 
---
= ONTAP Select ネットワークの概念と特性
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
まず、ONTAP Select環境に適用される一般的なネットワークの概念を理解してください。次に、シングルノードクラスタとマルチノードクラスタで利用可能な具体的な特性とオプションについて詳しく見ていきましょう。



== 物理ネットワーク

物理ネットワークは、基盤となるレイヤ2スイッチングインフラを提供することで、ONTAP Selectクラスタの導入を主にサポートします。物理ネットワークに関連する構成には、ハイパーバイザーホストとより広範なスイッチ化されたネットワーク環境の両方が含まれます。



=== ホストNICオプション

各ONTAP Selectハイパーバイザーホストは、2つまたは4つの物理ポートで構成する必要があります。選択する具体的な構成は、以下のようないくつかの要因によって異なります：

* クラスタに1つまたは複数のONTAP Selectホストが含まれているかどうか
* どのハイパーバイザーオペレーティングシステムが使用されていますか
* 仮想スイッチの設定方法
* リンクで LACP が使用されているかどうか




=== 物理スイッチの構成

物理スイッチの構成がONTAP Select導入をサポートしていることを確認する必要があります。物理スイッチは、ハイパーバイザーベースの仮想スイッチと統合されています。選択する具体的な構成は、いくつかの要因によって決まります。主な検討事項は以下のとおりです：

* 内部ネットワークと外部ネットワークの分離をどのように維持しますか？
* データネットワークと管理ネットワークの分離を維持しますか？
* レイヤ2 VLANはどのように設定されますか？




== 論理ネットワーク

ONTAP Selectは2つの異なる論理ネットワークを使用し、トラフィックを種類別に分離します。具体的には、クラスタ内のホスト間だけでなく、ストレージクライアントやクラスタ外の他のマシンとの間でもトラフィックが流れる可能性があります。ハイパーバイザーによって管理される仮想スイッチは、論理ネットワークのサポートに役立ちます。



=== 内部ネットワーク

マルチノードクラスタ展開では、個々のONTAP Selectノードは、隔離された「内部」ネットワークを使用して通信します。このネットワークは、ONTAP Selectクラスタ内のノードの外部では公開または利用できません。


NOTE: 内部ネットワークは、マルチノードクラスタの場合にのみ存在します。

内部ネットワークには次の特性があります：

* ONTAPクラスタ内トラフィックの処理に使用されます。以下が含まれます：
+
** クラスタ
** 高可用性インターコネクト（HA-IC）
** RAID同期ミラー（RSM）


* VLANに基づく単一のレイヤ2ネットワーク
* 静的IPアドレスはONTAP Selectによって割り当てられます：
+
** IPv4のみ
** DHCPは使用されていません
** リンクローカルアドレス


* MTUサイズはデフォルトで9000バイトで、7500～9000の範囲（両端を含む）で調整できます




=== 外部ネットワーク

外部ネットワークは、ONTAP Selectクラスタのノードと外部ストレージクライアント、およびその他のマシン間のトラフィックを処理します。外部ネットワークはすべてのクラスタ展開の一部であり、以下の特性があります：

* ONTAPトラフィックの処理に使用されます。次のものが含まれます：
+
** データ（NFS、CIFS、iSCSI）
** 管理（クラスタおよびノード、オプションでSVM）
** クラスタ間（オプション）


* オプションでVLANをサポートします：
+
** データポートグループ
** 管理ポートグループ


* 管理者の設定選択に基づいて割り当てられるIPアドレス：
+
** IPv4またはIPv6


* MTUサイズはデフォルトで1500バイトです（調整可能）


外部ネットワークは、あらゆる規模のクラスタに存在します。



== 仮想マシンのネットワーク環境

ハイパーバイザー ホストは、複数のネットワーク機能を提供します。

ONTAP Selectは、仮想マシンを通じて公開される以下の機能に依存しています：

仮想マシン ポート:: ONTAP Select で使用できるポートがいくつかあります。それらは、クラスタのサイズなど、いくつかの要因に基づいて割り当てられ、使用されます。
仮想スイッチ:: ハイパーバイザー環境内の仮想スイッチソフトウェア（vSwitch（VMware）またはOpen vSwitch（KVM））は、仮想マシンによって公開されるポートを物理イーサネットNICポートに接続します。環境に応じて、ONTAP SelectホストごとにvSwitchを設定する必要があります。

