---
sidebar: sidebar 
permalink: concept_api_understanding_scripts.html 
keywords: rest api, deploy rest api, rest, python, python scripts, understanding 
summary: サンプルPythonスクリプトを使用すると、さまざまなタスクを実行できます。実際のDeployインスタンスで使用する前に、スクリプトの内容を理解しておく必要があります。 
---
= ONTAP Select Deploy の Python スクリプトについて
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
サンプルPythonスクリプトを使用すると、さまざまなタスクを実行できます。実際のDeployインスタンスで使用する前に、スクリプトの内容を理解しておく必要があります。



== 共通の設計特性

これらのスクリプトは、以下の共通の特徴に基づいて設計されています。

* クライアントマシンのコマンドラインインターフェースから実行する 適切に設定されたクライアントマシンであれば、どのマシンからでもPythonスクリプトを実行できます。詳細については、_始める前に_をご覧ください。
* CLI入力パラメータを受け入れる 各スクリプトは、入力パラメータを介してCLIで制御されます。
* 入力ファイルの読み込み 各スクリプトは、その目的に応じて入力ファイルを読み込みます。クラスタを作成または削除する際には、JSON設定ファイルを提供する必要があります。ノードライセンスを追加する際には、有効なライセンスファイルを提供する必要があります。
* 共通サポートモジュールを使用する 共通サポートモジュール_deploy_requests.py_には、単一のクラスが含まれています。これは各スクリプトによってインポートされ、使用されます。




== クラスタを作成します。

cluster.pyスクリプトを使用してONTAP Selectクラスタを作成できます。CLIパラメータとJSON入力ファイルの内容に基づいて、以下のようにスクリプトをデプロイ環境に合わせて変更できます。

* ハイパーバイザー：デプロイ先のリリースに応じて、ESXiまたはKVMにデプロイできます。ESXiにデプロイする場合、ハイパーバイザーはvCenterで管理することも、スタンドアロンホストとして動作することも可能です。
* クラスターサイズ：シングルノードまたはマルチノードのクラスターを導入できます。
* 評価版または本番環境用ライセンス　評価版ライセンスまたは購入した本番環境用ライセンスを使用してクラスターをデプロイできます。


スクリプトのCLI入力パラメータは次のとおりです：

* Deploy サーバのホスト名または IP アドレス
* 管理者ユーザーアカウントのパスワード
* JSON設定ファイルの名前
* メッセージ出力の詳細表示フラグ




== ノードライセンスを追加する

本番環境クラスターをデプロイする場合は、スクリプト_add_license.py_を使用して各ノードにライセンスを追加する必要があります。ライセンスは、クラスターをデプロイする前でも後でも追加できます。

スクリプトのCLI入力パラメータは次のとおりです：

* Deploy サーバのホスト名または IP アドレス
* 管理者ユーザーアカウントのパスワード
* ライセンスファイルの名前
* ライセンスを追加する権限を持つ ONTAP ユーザー名
* ONTAP ユーザーのパスワード




== クラスタを削除

スクリプト_delete_cluster.py_を使用して、既存のONTAP Selectクラスターを削除できます。

スクリプトのCLI入力パラメータは次のとおりです：

* Deploy サーバのホスト名または IP アドレス
* 管理者ユーザーアカウントのパスワード
* JSON設定ファイルの名前

