---
sidebar: sidebar 
permalink: concept_api_before_browser.html 
keywords: rest api, deploy rest api, rest, access browser, before you begin 
summary: Deployのオンラインドキュメントページを使用する前に、いくつか注意すべき点があります。 
---
= ブラウザで ONTAP Select Deploy API にアクセスする前に
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Deployのオンラインドキュメントページを使用する前に、いくつか注意すべき点があります。



== 導入計画

特定のデプロイメントや管理タスクを実行する際にAPI呼び出しを行う予定がある場合は、デプロイメントプランを作成することを検討してください。これらの計画は正式なものも非公式なものもあり、一般的には目標と使用するAPI呼び出しが含まれています。詳細については、Deploy REST APIを使用したワークフロープロセスを参照してください。



== JSONの例とパラメータ定義

各API呼び出しは、一貫した形式を用いてドキュメントページで説明されています。内容には、実装に関する注意事項、クエリパラメータ、HTTPステータスコードが含まれます。さらに、APIリクエストとレスポンスで使用されるJSONの詳細を以下のように表示できます：

* Example Value API呼び出しで_Example Value_をクリックすると、その呼び出しの典型的なJSON構造が表示されます。必要に応じて例を修正し、リクエストの入力として使用できます。
* モデル _Model_をクリックすると、JSONパラメータの完全なリストが表示され、各パラメータの説明が表示されます。




== API 呼び出しを行う際の注意点

Deploy に関するドキュメント ページを使用して実行するすべての API 操作は、ライブ操作です。設定データやその他のデータを誤って作成、更新、または削除しないように注意してください。
