---
sidebar: sidebar 
permalink: concept_nw_internal_external.html 
keywords: ontap select, internal network, external network 
summary: 内部および外部のONTAP Selectネットワークの特性。 
---
= ONTAP Select内部ネットワークと外部ネットワーク
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select内部ネットワークと外部ネットワークの特徴。



== ONTAP Select 内部ネットワーク

内部ONTAP Selectネットワークは、製品のマルチノード版にのみ存在し、ONTAP Selectクラスタにクラスタ通信、HAインターコネクト、および同期レプリケーションサービスを提供します。このネットワークには、次のポートとインターフェイスが含まれます：

* *e0c、e0d。*クラスタネットワークLIFをホストする
* *e0e.*RSM LIFのホスティング
* *e0f.*HAインターコネクトLIFのホスティング


このネットワークのスループットとレイテンシは、ONTAP Selectクラスタのパフォーマンスと回復力を決定する上で非常に重要です。クラスタのセキュリティを確保し、システムインターフェイスが他のネットワーク トラフィックから分離されるようにするには、ネットワーク分離が必要です。したがって、このネットワークはONTAP Selectクラスタ専用で使用する必要があります。


NOTE: Selectクラスタトラフィック以外のトラフィック（アプリケーショントラフィックや管理トラフィックなど）にSelect内部ネットワークを使用することはサポートされていません。ONTAP内部VLAN上に他のVMやホストを配置することはできません。

内部ネットワークを通過するネットワーク パケットは、専用のVLANタグ付きレイヤ2ネットワーク上になければなりません。これは、次のいずれかのタスクを実行することで実現できます。

* 内部仮想NIC（e0cからe0f）へのVLANタグ付きポートグループの割り当て（VSTモード）
* 上流スイッチが提供するネイティブVLANを使用する（ただし、ネイティブVLANが他のトラフィックに使用されていない場合に限る。VLAN IDのないポートグループを割り当てる、つまりESTモードを使用する）


いずれの場合も、内部ネットワーク トラフィックの VLAN タグ付けは ONTAP Select VM の外部で行われます。


NOTE: ESXi標準および分散vSwitchesのみがサポートされています。その他の仮想スイッチまたはESXiホスト間の直接接続はサポートされていません。内部ネットワークは完全にオープンである必要があります。NATまたはファイアウォールはサポートされていません。

ONTAP Selectクラスタ内では、内部トラフィックと外部トラフィックは、ポートグループと呼ばれる仮想レイヤ2ネットワークオブジェクトを使用して分離されます。これらのポートグループに対する正しいvSwitchの割り当ては、特にクラスタ、HAインターコネクト、およびミラーレプリケーションサービスを提供する内部ネットワークにとって非常に重要です。これらのネットワークポートへのネットワーク帯域幅が不足すると、パフォーマンスが低下したり、クラスタノードの安定性に影響が出たりする可能性があります。したがって、4、6、8、10、12ノードのクラスタでは、内部ONTAP Selectネットワークは10Gb接続を使用する必要があります。1Gb NICはサポートされていません。ただし、外部ネットワークに対してトレードオフを行うことができます。ONTAP Selectクラスタへの受信データのフローを制限しても、その信頼性の高い動作能力に影響を与えないためです。

2ノードクラスタでは、内部トラフィックに4つの1Gbポートを使用するか、4ノードクラスタで必要な2つの10Gbポートの代わりに1つの10Gbポートを使用できます。サーバーに4枚の10Gb NICカードを搭載できない環境では、内部ネットワーク用に2枚の10Gb NICカードを、外部ONTAPネットワーク用に2枚の1Gb NICを使用できます。



=== 内部ネットワークの検証とトラブルシューティング

マルチノード クラスター内の内部ネットワークは、ネットワーク接続チェッカー機能を使用して検証できます。この関数は、 `network connectivity-check start`コマンドを実行するDeploy CLIから呼び出すことができます。

次のコマンドを実行して、テストの出力を表示します。

[listing]
----
network connectivity-check show --run-id X (X is a number)
----
このツールは、マルチノード Select クラスタ内の内部ネットワークのトラブルシューティングにのみ役立ちます。このツールは、シングルノード クラスタ（vNAS 構成を含む）、ONTAP Deploy から ONTAP Select への接続、またはクライアント側の接続の問題のトラブルシューティングには使用しないでください。

クラスタ作成ウィザード（ONTAP Deploy UIの一部）には、マルチノード クラスターの作成中に使用できるオプションの手順として内部ネットワーク チェッカーが含まれています。マルチノード クラスターでは内部ネットワークが重要な役割を果たすため、このステップをクラスター作成ワークフローの一部にすると、クラスター作成操作の成功率が向上します。

ONTAP Deploy 2.10以降では、内部ネットワークで使用されるMTUサイズを7,500～9,000の間で設定できます。ネットワーク接続チェッカーは、7,500～9,000のMTUサイズをテストするためにも使用できます。デフォルトのMTU値は、仮想ネットワークスイッチの値に設定されます。環境にVXLANのようなネットワークオーバーレイが存在する場合は、そのデフォルト値をより小さな値に置き換える必要があります。



== ONTAP Select 外部ネットワーク

ONTAP Select外部ネットワークは、クラスタによるすべてのアウトバウンド通信を担当するため、シングルノード構成とマルチノード構成の両方に存在します。このネットワークには内部ネットワークのような厳密に定義されたスループット要件はありませんが、管理者はクライアントとONTAP VM間のネットワーク ボトルネックを作らないように注意する必要があります。パフォーマンスの問題がONTAP Selectの問題として誤って特徴付けられる可能性があるためです。


NOTE: 内部トラフィックと同様に、外部トラフィックもvSwitchレイヤー（VST）と外部スイッチレイヤー（EST）でタグ付けできます。さらに、外部トラフィックは、VGTと呼ばれるプロセスでONTAP Select VM自体によってタグ付けすることもできます。詳細については、link:concept_nw_data_mgmt_separation.html["データトラフィックと管理トラフィックの分離"]のセクションを参照してください。

以下の表は、ONTAP Select内部ネットワークと外部ネットワークの主な違いを示しています。

*内部ネットワークと外部ネットワークのクイックリファレンス*

[cols="3*"]
|===
| 説明 | 内部ネットワーク | 外部ネットワーク 


| ネットワークサービス | クラスタHA/IC RAID SyncMirror（RSM） | データ管理インタークラスタ（SnapMirrorおよびSnapVault） 


| ネットワーク分離 | 必須 | オプション 


| フレームサイズ（MTU） | 7,500～9,000 | 1,500（デフォルト）9,000（サポート対象） 


| IPアドレスの割り当て | 自動生成 | ユーザ定義 


| DHCPのサポート | × | × 
|===


=== NICチーミング

内部ネットワークと外部ネットワークの両方が、高いパフォーマンスと耐障害性を実現するために必要な帯域幅と回復力特性の両方を備えていることを確認するには、物理ネットワークアダプタのチーミングが推奨されます。単一の10Gbリンクを備えた2ノードクラスタ構成がサポートされています。ただし、NetAppが推奨するベストプラクティスは、ONTAP Selectクラスタの内部ネットワークと外部ネットワークの両方でNICチーミングを使用することです。



=== MACアドレスの生成

すべてのONTAP Selectネットワークポートに割り当てられたMACアドレスは、付属の導入ユーティリティによって自動的に生成されます。このユーティリティは、NetApp固有のプラットフォーム固有の組織固有識別子（OUI）を使用して、FASシステムとの競合がないことを確認します。このアドレスのコピーは、ONTAP Selectインストール VM（ONTAP Deploy）内の内部データベースに保存され、将来のノード導入時に誤って再割り当てされるのを防ぎます。管理者は、ネットワークポートに割り当てられたMACアドレスをいかなる場合も変更してはなりません。
