---
sidebar: sidebar 
permalink: concept_terminology.html 
keywords: terminology, key concepts, concepts 
summary: ONTAP Selectの調査を開始して導入を計画する際には、まず用語と主要な概念を理解しておくと役立ちます。 
---
= ONTAP Selectの用語と主要概念
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Selectの調査を開始して導入を計画する際には、まず用語と主要な概念を理解しておくと役立ちます。

ONTAP Select Deploy:: ONTAP Select Deployは、ONTAP Selectクラスタの導入に使用する管理ユーティリティです。Deployユーティリティは、専用のLinux仮想マシンで実行されます。Deployユーティリティには、WebユーザインターフェイスCLI管理シェル、およびREST APIを使用してアクセスできます。
カーネルベースの仮想マシン:: カーネルベース仮想マシン（KVM）は Linux カーネルの仮想化機能であり、ハイパーバイザー プラットフォームとして機能します。幅広いゲスト オペレーティング システムがサポートされています。
ハイパーバイザー ホストと ONTAP Select ノード:: _ハイパーバイザー ホスト_は、ONTAP Select仮想マシンをホストするコア ハードウェア プラットフォームです。ONTAP Select仮想マシンがハイパーバイザー ホストに導入されてアクティブになると、_ONTAP Selectノード_とみなされます。
ONTAP Selectクラスタ:: 1、2、4、6、8、10、または12ノードで構成される_ONTAP Selectクラスタ_を作成できます。マルチノードクラスタには、必ず1つ以上のHAペアが含まれます。たとえば、4ノードクラスタは2つのHAペアで構成されます。シングルノードクラスタにはHA機能はありません。
ハイパーバイザー ホスト環境の準備:: Deploy管理ユーティリティを使用してONTAP Selectクラスタを導入する前に、ONTAP Selectを実行するハイパーバイザーホスト（ストレージ環境やネットワーク環境を含む）を準備する必要があります。このホストの事前設定は、現在の要件と制限事項に基づいて、ONTAP Select製品の外部で実行されます。
評価と本番環境への展開:: すべてのONTAP Selectノードは、_評価ライセンス_または_購入ライセンス_のいずれかで実行されます。評価ライセンスを使用すると、本番環境に導入する前にONTAP Selectを評価できます。評価ライセンスは自動的に生成され、適用されます。本番環境にクラスタを導入する場合は、次の項目を選択してライセンスを購入する必要があります：
+
--
* ライセンス モデル
* ストレージ容量
* プラットフォーム ライセンス製品


--
容量階層ライセンス モデル:: Capacity Tiersライセンスモデルは、ONTAP Select環境のストレージのライセンスを取得する際の元のオプションです。これは、NetApp AFFおよびFASで使用されるONTAPモデルに基づいています。ノードごとに個別のライセンスが必要です。ストレージ容量はノードに紐付けられ、永続的に利用可能です（更新は不要です）。
Capacity Poolsライセンス モデル:: Capacity Poolsライセンスモデルは、Deploy 2.10を使用したONTAP Select 9.5で導入されました。ストレージCapacity Poolごとに個別のライセンスが必要です。Capacity PoolライセンスはLicense Managerインスタンス（つまりDeployインスタンス）にロックされており、購入条件に基づいて更新する必要があります。組織内では、任意の数のCapacity Poolsをライセンス取得して使用できます。ただし、Capacity PoolsはONTAP Selectノードで共有されるため、通常、Capacity Tiersライセンスよりも必要なライセンス数が少なくなります。
ライセンス マネージャ:: ライセンスマネージャーは、キャパシティプールライセンスをサポートするソフトウェアコンポーネントです。現在は、Deploy管理ユーティリティの一部となっています。LMは、管理する共有プールからONTAP Selectノードにストレージをリースします。_License Lock ID_は、各LMインスタンス、ひいては各Deployインスタンスを一意に識別する数値文字列です。ライセンスファイルを生成するには、Capacity Poolライセンスのシリアル番号とLLIDの両方を使用する必要があります。
プラットフォームライセンスの提供内容:: ライセンスを購入する際に ONTAP Select 仮想マシンのサイズ機能を決定する 3 つのライセンス オファリングが用意されています。
+
--
* Standard
* Premium
* プレミアムXL


--


詳細については、以下の2つのセクションlink:concept_workflow_deploy.html["Plan"]およびlink:concept_lic_evaluation.html["ライセンス"]を参照してください。

ストレージプールとデータストア:: ONTAP Select _ストレージプール_は、基盤となる物理ストレージを抽象化して隠蔽するように設計された論理データ コンテナです。ストレージプールはハイパーバイザーに依存しません。ESXiハイパーバイザー ホストにデプロイした場合、ONTAP Selectストレージプールは、VMware _データストア_と同義です。
クラスタ MTU:: Cluster MTUは、ONTAP Selectマルチノードクラスタで使用される内部ネットワークで使用されるMTUサイズを設定できる機能です。Deploy管理ユーティリティは、HAペアを設定する際に、ネットワーク環境に合わせてMTUサイズを調整します。値を手動で設定することもできます。
ONTAP Select vNAS:: ONTAP Select vNASソリューションを使用すると、ONTAP Selectノードは外部ストレージ上のVMwareデータストアにアクセスできます。ONTAP Select vNASでは、ローカルRAIDコントローラは不要になります。RAID機能はリモートストレージによって提供されることが前提となります。ONTAP Select vNASは次の方法で設定できます：
+
--
* VMware vSAN
* 汎用外部ストレージアレイ


--


どちらの場合も、ONTAP Selectクラスタを作成する前、または既存ノードのストレージ容量を拡張する前に、外部ストレージを設定する必要があります。

ESXi VM上でのノードの再ホスト:: ONTAP Select vNAS ソリューション（VMware vSAN または汎用外部ストレージアレイ）を介して利用可能な外部ストレージを使用するクラスタを導入する場合、ONTAP Select ノードをホストする ESXi 仮想マシンは、次の VMware 機能を利用した操作によって移動できます：
+
--
* vMotion
* 高可用性（HA）
* Distributed Resource Scheduler（DRS）
+
ONTAP Select Deployユーティリティは、次のようなクラスタでの処理の実行の一環として、仮想マシンの移動を検出します：

* クラスタオンライン
* クラスタオフライン
* ストレージを追加
+
仮想マシンが移動すると、Deployユーティリティは内部データベースを更新し、新しいESXiホストを設定します。ONTAP Selectノードで実行されるすべての処理は、仮想マシンの移動とDeployの更新が完了するまでブロックされます。



--
KVM用vSwitch:: Open vSwitch（OVS）は、複数のネットワークプロトコルをサポートする仮想スイッチのソフトウェア実装です。OVSはオープンソースであり、Apache License 2.0に基づいて利用可能です。
メディエーターサービス:: ONTAP Select Deployユーティリティには、アクティブな2ノードクラスタ内のノードに接続するメディエーターサービスが含まれています。このサービスは、各HAペアを監視し、障害の管理を支援します。



CAUTION: アクティブな2ノードクラスタが1つ以上ある場合、クラスタを管理するONTAP Select Deploy仮想マシンは、常に稼働している必要があります。Deploy仮想マシンが停止すると、メディエーターサービスが利用できなくなり、2ノードクラスタのHA機能が失われます。

MetroCluster SDS:: MetroCluster SDSは、2ノードONTAP Selectクラスタをデプロイする際に、追加の構成オプションを提供する機能です。一般的な2ノードROBO導入とは異なり、MetroCluster SDSノードは、はるかに大きな距離で分離することができます。この物理的な分離により、ディザスタリカバリなどの追加のユースケースが可能になります。MetroCluster SDSを使用するには、プレミアムライセンス以上が必要です。さらに、ノード間のネットワークは、最小レイテンシ要件をサポートする必要があります。
認証情報ストア:: デプロイ資格情報ストアは、アカウント資格情報を保持する安全なデータベースです。主に、新しいクラスタの作成の一環としてハイパーバイザーホストを登録するために使用されます。詳細については、link:concept_workflow_deploy.html["Plan"]セクションを参照してください。
Storage Efficiency:: ONTAP Selectには、FASおよびAFFアレイに搭載されているストレージ効率化オプションと同様のストレージ効率化オプションが用意されています。概念的には、DAS（Direct-Attached Storage）SSDを使用するONTAP Select（プレミアムライセンスを使用）は、AFFアレイに似ています。HDDを使用するDAS構成およびすべてのvNAS構成は、FASアレイと同様と見なす必要があります。2つの構成の主な違いは、DAS SSDを使用するONTAP Selectでは、インラインアグリゲートレベルの重複排除とアグリゲートレベルのバックグラウンド重複排除がサポートされることです。残りのストレージ効率化オプションは、どちらの構成でも使用できます。
+
--
vNASのデフォルト構成では、単一インスタンスデータログ（SIDL）と呼ばれる書き込み最適化機能が有効になります。ONTAP Select 9.6以降のリリースでは、バックグラウンドONTAPストレージ効率機能は、SIDLが有効になっている場合に認定されます。詳細については、link:concept_stor_concepts_chars.html["詳細分析"]セクションを参照してください。

--
クラスタの更新:: クラスタを作成したあと、ONTAPまたはハイパーバイザー管理ツールを使用して、Deployユーティリティ以外でクラスタまたは仮想マシンの設定を変更できます。仮想マシンを移行すると、構成が変更される場合もあります。これらの変更が発生した場合、Deployユーティリティは自動的に更新されず、クラスタの状態と同期が取れなくなる可能性があります。クラスタ更新機能を使用して、Deploy構成データベースを更新できます。クラスタの更新は、Deploy WebユーザーインターフェイスCLI管理シェル、およびREST APIを使用して実行できます。
ソフトウェアRAID:: 直接接続ストレージ（DAS）を使用する場合、RAID機能は従来、ローカルハードウェアRAIDコントローラを介して提供されます。代わりに、ノードを_ソフトウェアRAID_を使用するように構成できます。ONTAP SelectノードはRAID機能を提供します。ソフトウェアRAIDを使用する場合、ハードウェアRAIDコントローラはもはや必要ありません。


[[ontap-select-image-install]]
ONTAP Selectイメージのインストール:: Deploy管理ユーティリティには、ONTAP Selectのバージョンが1つだけ含まれています。収録されているバージョンは、リリース時点で入手可能な最新バージョンです。ONTAP Selectイメージインストール機能を使用すると、以前のバージョンのONTAP SelectをDeployユーティリティのインスタンスに追加でき、ONTAP Selectクラスタの導入時に使用できます。link:task_cli_deploy_image_add.html["詳細については、ONTAP Select の画像を追加してください"]を参照してください。



NOTE: 追加する ONTAP Select イメージは、Deploy インスタンスに含まれている元のバージョンよりも前のバージョンのみにしてください。Deploy を更新せずに ONTAP Select の新しいバージョンを追加することはサポートされていません。

ONTAP Selectクラスタのデプロイ後の管理:: ONTAP Select クラスタを導入したら、ハードウェアベースの ONTAP クラスタと同様にクラスタを設定できます。たとえば、System Manager または標準の ONTAP コマンドラインインターフェイスを使用して ONTAP Select クラスタを設定できます。


.関連情報
link:task_cli_deploy_image_add.html["ONTAP SelectイメージをDeployに追加"]
