---
sidebar: sidebar 
permalink: reference_plan_best_practices.html 
keywords: plan, planning, best practices, recommendations 
summary: ONTAP Select 導入を計画する際に考慮すべきベスト プラクティスがあります。 
---
= ONTAP Select 導入のベストプラクティスの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 導入を計画する際に考慮すべきベスト プラクティスがあります。



== ストレージ

ストレージに関しては、以下のベストプラクティスを検討してください。



=== オールフラッシュまたは汎用フラッシュアレイ

オールフラッシュVSANまたは汎用フラッシュアレイを使用したONTAP Select仮想NAS（vNAS）の導入では、SSD以外のDASストレージを使用したONTAP Selectのベストプラクティスに従う必要があります。



=== 外部ストレージ

次の推奨事項に従う必要があります。

* ONTAP Select ネットワークと外部ストレージ用の専用ネットワーク ポート、帯域幅、およびvSwitch構成を定義します
* ストレージ使用量を制限するには、容量オプションを設定します（ONTAP Selectは外部ストレージプールの全容量を消費することはできません）
* すべての外部ストレージアレイで、可能な場合は利用可能な冗長性とHA機能を使用していることを確認してください




=== ハイパーバイザーコアハードウェア

単一のONTAP Select アグリゲート内のすべてのドライブは同じタイプである必要があります。たとえば、HDDとSSDのドライブを同じアグリゲート内で混在させないでください。



=== RAIDコントローラ

サーバRAIDコントローラはライトバックモードで動作するように設定する必要があります。書き込みワークロードのパフォーマンスに問題が発生する場合は、コントローラの設定を確認し、ライトスルーまたはライトアラウンドが有効になっていないことを確認してください。

物理サーバに、ローカルに接続されたすべてのディスクを管理する単一のRAIDコントローラが含まれている場合、NetAppでは、サーバOSに個別のLUNを作成し、ONTAP Select用に1つ以上のLUNを作成することを推奨します。ブートディスクが破損した場合、このベストプラクティスにより、管理者はONTAP Selectに影響を与えることなくOS LUNを再作成できます。

RAIDコントローラキャッシュは、NVRAMパーティションを対象とするものだけでなく、受信するすべてのブロック変更を保存するために使用されます。したがって、RAIDコントローラを選択する際は、利用可能な最大のキャッシュを持つものを選択してください。キャッシュが大きいほど、ディスクフラッシュの頻度が減り、ONTAP Select VM、ハイパーバイザー、およびサーバー上に共存するすべてのコンピューティングVMのパフォーマンスが向上します。



=== RAIDグループ

最適なRAIDグループのサイズは8～12台のドライブです。RAIDグループあたりのドライブの最大数は24台です。

ONTAP SelectノードあたりでサポートされるNVMeドライブの最大数は14です。

スペア ディスクは必須ではありませんが、推奨されます。NetAppでは、RAIDグループごとに1つのスペアを使用することも推奨していますが、すべてのRAIDグループに対してグローバル スペアを使用することもできます。たとえば、3つのRAIDグループに対して2つのスペアを使用でき、各RAIDグループは8～12台のドライブで構成されます。

ONTAP Select では、RAIDグループ内のLUN数を増やしてもパフォーマンス上のメリットは得られません。複数のLUNは、SATA/NL-SAS構成のベストプラクティスに従う場合、またはハイパーバイザーファイルシステムの制限を回避する場合にのみ使用する必要があります。



=== VMware ESXiホスト

NetAppでは、システム ディスクをホストするデータストアには、ESXi 8.0 以降と NVMe ディスクを使用することを推奨しています。この構成により、NVRAM パーティションに最適なパフォーマンスが提供されます。


NOTE: ESXi 8.0以降にインストールする場合、ONTAP Selectは、システム ディスクがSSD上にあるかNVMeディスク上にあるかに関係なく、vNVMEeドライバーを使用します。これにより、VMハードウェア レベルが13に設定され、ESXi 8.0以降と互換性を持つようになります。

ONTAP Select ネットワークおよび外部ストレージ（iSCSI または NFS を使用する場合の VMware vSAN および汎用ストレージ アレイのトラフィック）用に、専用ネットワーク ポート、帯域幅、および vSwitch 構成を定義します。

ストレージ使用量を制限するには、容量オプションを設定します（ONTAP Selectは外部vNASデータストアの全容量を消費することはできません）。

汎用外部ストレージアレイはすべて、可能な限り利用可能な冗長性およびHA機能を使用するようにしてください。



=== VMware Storage vMotion

新しいホストで使用可能な容量は、ONTAP SelectノードでVMware Storage vMotionを使用するかどうかを決定する際の唯一の要素ではありません。基盤となるストレージタイプ、ホスト構成、およびネットワーク機能は、元のホストと同じワークロードを維持できる必要があります。



== ネットワーク

ネットワーク構築にあたっては、以下のベストプラクティスを考慮する必要があります。



=== 重複するMACアドレス

複数の Deploy インスタンスが重複する MAC アドレスを割り当てる可能性を排除するために、レイヤ 2 ネットワークごとに 1 つの Deploy インスタンスを使用して ONTAP Select クラスタまたはノードを作成または管理する必要があります。



=== EMSメッセージ

ONTAP Select 2ノードクラスタでは、ストレージフェイルオーバーが無効になっていることを示すEMSメッセージがないか、注意深く監視する必要があります。これらのメッセージは、メディエーターサービスへの接続が失われたことを示しており、直ちに修正する必要があります。



=== ノード間のレイテンシ

2つのノード間のネットワークは、平均遅延5msに加え、周期的な5msのジッタにも対応できる必要がある。クラスタをデプロイする前に、ONTAP Select製品アーキテクチャとベストプラクティスに関する技術レポートに記載されている手順を使用してネットワークをテストしてください。



=== 負荷分散

内部と外部の両方のONTAP Selectネットワーク全体でロード バランシングを最適化するには、発信元仮想ポートに基づくルートのロード バランシング ポリシーを使用します。



=== 複数のレイヤ 2 ネットワーク

データトラフィックが複数のレイヤ2ネットワークにまたがり、VLANポートの使用が必要な場合、または複数のIPspaceを使用している場合は、VGTを使用する必要があります。



=== 物理スイッチの構成

VMwareは、ESXiホストに接続されているスイッチポートのSTP設定をPortfastにすることを推奨しています。スイッチポートでSTPをPortfastに設定しないと、ONTAP Selectのアップリンク障害に対する耐性に影響する可能性があります。LACPを使用する場合、LACPタイマー設定は高速（1秒）にしてください。ロード バランシング ポリシーは、ポートグループでは「IPハッシュに基づくルーティング」に設定し、LAGでは「送信元および宛先IPアドレス、TCP/UDPポート、VLAN」に設定する必要があります。



=== KVM の仮想スイッチ オプション

外部ネットワークと内部ネットワーク（マルチノードクラスタのみ）をサポートするために、各ONTAP Selectホストで仮想スイッチを設定する必要があります。マルチノードクラスタを導入する際には、内部クラスタネットワークのネットワーク接続をテストする必要があります。

ハイパーバイザーホスト上でOpen vSwitchを設定する方法の詳細については、link:https://www.netapp.com/media/13134-tr4613.pdf["KVM上のONTAP Select製品のアーキテクチャとベストプラクティス"^]テクニカルレポートを参照してください。



== HA

高可用性については、以下のベストプラクティスを考慮する必要があります。



=== バックアップをデプロイする

クラスタの作成後も含め、 Deploy 構成データを定期的にバックアップすることを推奨します。メディエーター構成データがバックアップに含まれるため、 2 ノードクラスタでは特に重要です。

クラスタを作成または導入したら、link:task_cli_clusters.html["ONTAP Select Deploy構成データをバックアップする"]する必要があります。



=== ミラーアグリゲート

ミラーリングされたアグリゲートの存在は、プライマリアグリゲートの最新（RPO 0）コピーを提供するために必要ですが、プライマリアグリゲートの空き容量が不足しないように注意してください。プライマリアグリゲートの空きスペースが少ない状態になると、ONTAPがストレージギブバックのベースラインとして使用される共通のSnapshotコピーを削除する可能性があります。これは、クライアントの書き込みに対応するために設計どおりに機能します。ただし、フェイルバック時に共通のSnapshotコピーがない場合、ONTAP Selectノードはミラーリングされたアグリゲートから完全なベースラインを実行する必要があります。シェアードナッシング環境では、この処理にかなりの時間がかかる場合があります。


NOTE: NetAppでは、最適なストレージパフォーマンスと可用性を実現するために、ミラーアグリゲートに少なくとも20%の空きスペースを維持することを推奨しています。ミラーリングされていないアグリゲートの推奨値は10%ですが、ファイルシステムは追加の10%のスペースを使用して増分変更を吸収できます。ONTAPのcopy-on-write Snapshotベースアーキテクチャにより、増分変更によってミラーアグリゲートのスペース使用率が増加します。これらのベストプラクティスに従わないと、パフォーマンスに悪影響を及ぼす可能性があります。ハイアベイラビリティテイクオーバーは、データアグリゲートがミラーアグリゲートとして設定されている場合にのみサポートされます。



=== NICアグリゲーション、チーミング、およびフェイルオーバー

ONTAP Selectは2ノードクラスタ用の単一の10Gbリンクをサポートしますが、ONTAP Selectクラスタの内部ネットワークと外部ネットワークの両方でNICアグリゲーションまたはNICチーミングによるハードウェア冗長性を確保することがNetAppのベストプラクティスです。

NICに複数の特定用途向け集積回路（ASIC）が搭載されている場合、内部ネットワークと外部ネットワークのネットワーク構成をNICチーミングによって構築する際には、各ASICから1つのネットワークポートを選択してください。

NetApp では、ESXi と物理スイッチの両方で LACP モードをアクティブにすることを推奨しています。さらに、LACP タイマーは、物理スイッチ、ポート、ポート チャネル インターフェイス、および VMNIC では、高速（1 秒）に設定する必要があります。

LACPで分散型vSwitchを使用する場合、NetAppでは、ポートグループ上のロード バランシング ポリシーをIPハッシュに基づいてルーティング、LAG上の送信元および宛先IPアドレス、TCP/UDPポート、およびVLANに設定することを推奨します。



=== 2ノード伸長HA（MetroCluster SDS）のベストプラクティス

MetroCluster SDS を作成する前に、 ONTAP Deploy 接続性チェッカーを使用して、 2 つのデータセンター間のネットワーク遅延が許容範囲内であることを確認します。

仮想ゲストタグ付け（VGT）と2ノードクラスタを使用する場合には、さらに注意すべき点があります。2ノードクラスタ構成では、ONTAPが完全に利用可能になる前に、ノード管理IPアドレスを使用してメディエーターへの早期接続を確立します。したがって、ノード管理LIF（ポートe0a）にマッピングされたポートグループでは、外部スイッチタグ付け（EST）と仮想スイッチタグ付け（VST）のみがサポートされます。さらに、管理トラフィックとデータトラフィックの両方が同じポートグループを使用している場合、2ノードクラスタ全体でESTとVSTのみがサポートされます。
