---
sidebar: sidebar 
permalink: reference_plan_ots_storage.html 
keywords: plan, planning, storage, software raid, hardware raid, raid, nvme 
summary: ONTAP Select ホストストレージに関連して検討すべき計画上の問題がいくつかあります。 
---
= ONTAP Selectストレージおよび RAIDに関する考慮事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select ホストストレージに関連して検討すべき計画上の問題がいくつかあります。


NOTE: ESXi および KVM ホストの外部ストレージ サポート情報について説明します。詳細については、link:reference_plan_ots_vnas.html["VMware ESXi の要件"]およびlink:reference_plan_ots_kvm.html["KVMの要件"]を参照してください。



== ハードウェア RAID コントローラの要件

ONTAP Selectを導入するハイパーバイザーホストのRAIDコントローラは、いくつかの要件を満たす必要があります。


NOTE: ONTAP Selectを実行するホストでは、ハードウェアRAIDコントローラまたはONTAP Selectに付属のソフトウェアRAID機能を使用する場合、ローカルの物理ドライブが必要です。ONTAP Select vNASソリューションを使用して外部ストレージにアクセスする場合、ローカルRAIDコントローラおよびソフトウェアRAID機能は使用されません。

RAIDコントローラの最小要件は次のとおりです。

* 12Gbpsのスループット
* 512MBの内部バッテリ バックアップ式またはフラッシュ（SuperCAP）キャッシュ
* ライトバックモードで設定済み：
+
** フェイルバックモードを「ライトスルー」に設定（サポートされている場合）
** 「常に先読み」ポリシーを有効にする（サポートされている場合）


* RAID コントローラの背後にあるすべてのローカルディスクは、単一の RAID グループとして構成する必要があります。必要に応じて複数の RAID コントローラを使用します：
+
** データ整合性を維持するために不可欠な、RAIDグループのローカルドライブキャッシュを無効にします。


* 次のガイドラインに基づいて LUN 構成を実行します：
+
** RAIDグループのサイズが最大LUNサイズの64TBを超える場合は、RAIDグループ内の使用可能なストレージをすべて消費する、同じサイズの複数のLUNを構成します。
** RAIDグループのサイズが最大LUNサイズの64TBより小さい場合は、RAIDグループ内の使用可能なストレージをすべて消費する1つのLUNを設定します。






== ソフトウェアRAIDの要件

ハイパーバイザーに ONTAP Select クラスタを導入する場合は、ローカルハードウェア RAID コントローラの代わりに ONTAP Select が提供するソフトウェア RAID 機能を使用できます。ソフトウェア RAID を使用してクラスタを導入する前に、次の要件と制限事項を確認してください。



=== 一般要件

ソフトウェアRAIDを導入するための環境は、以下の主要要件を満たす必要があります：

* VMware ESXi 8.0 GA（ビルド20513097）以降
* ONTAP Selectプレミアムライセンス以上
* ローカル SSD ドライブのみ
* システムディスクとルートアグリゲートおよびデータアグリゲートの分離
* ホストにハードウェアRAIDコントローラがない



NOTE: ハードウェアRAIDコントローラが存在する場合は、追加の構成要件についてlink:concept_stor_concepts_chars.html["ストレージの詳細"]のセクションを参照してください。



=== ESXi固有の要件

* VMware ESXi 8.0 GA（ビルド20513097）以降
* VMware VMotion、HA、およびDRSはサポートされていません
* ONTAP Select 9.4以前からアップグレードされたノードでは、ソフトウェアRAIDを使用できません。この場合は、ソフトウェアRAID展開用に新しいノードを作成する必要があります。




=== KVM固有の要件

特定のソフトウェア パッケージ構成要件もあります。詳細については、link:https://docs.netapp.com/us-en/ontap-select/kvm-host-configuration-and-preparation-checklist.html#prepare-linux-server["Linuxサーバの準備"]の手順を参照してください。

KVMのメディア要件:: 使用するSSDフラッシュストレージデバイスは、以下の追加要件を満たす必要があります：
+
--
* SSDデバイスは、以下の方法により、Linuxホストに対して正確かつ継続的に自身の情報を報告する必要があります。
+
** # cat /sys/block/<device>/queue/rotational
+
これらのコマンドで報告される値は「0」でなければなりません。



* デバイスはHBAに接続されているか、場合によってはJBODモードで動作するように構成されたRAIDコントローラに接続されていることが想定されます。RAIDコントローラを使用する場合、デバイス機能は、RAID機能をオーバーレイせずにホストを通過する必要があります。JBODモードでRAIDコントローラを使用する場合は、RAIDドキュメントを確認するか、必要に応じてベンダーに連絡して、デバイスが回転速度を「0」として報告していることを確認する必要があります。
* ストレージコンポーネントは2つに分かれています。
+
** 仮想マシンのストレージ
+
これは、ONTAP Select仮想マシンをホストするために使用されるシステムデータを含むLVMプール（ストレージプール）です。LVMプールは、高耐久性のフラッシュデバイスによってバックアップされている必要があり、SAS、SATA、またはNVMeのいずれかを使用できます。パフォーマンス向上のため、NVMeデバイスの使用をお勧めします。

** データディスク
+
これは、データ管理に使用されるSASまたはSATA SSDドライブのセットです。SSDデバイスは、エンタープライズグレードで耐久性のあるものである必要があります。NVMeインターフェイスはサポートされていません。



* すべてのデバイスは512BPSでフォーマットする必要があります。


--




=== ONTAP Selectノードの構成

システムディスクをルートアグリゲートおよびデータアグリゲートから分離するために、各ONTAP Selectノードとハイパーバイザーホストを次のように設定する必要があります：

* システムストレージプールを作成する ONTAP Select システムデータ用のストレージプールを作成する必要があります。ONTAP Select ノードの設定の一部として、ストレージプールを接続する必要があります。
* 必要な物理ディスクを接続するハイパーバイザーホストには、必要な SSD ディスクが接続され、ONTAP Select 仮想マシンで使用できるようになっている必要があります。これらのドライブには、ルートアグリゲートとデータアグリゲートが格納されます。ONTAP Select ノードの設定の一環として、ストレージディスクを接続する必要があります。




== ストレージ容量の制限

ONTAP Select の導入を計画する際には、ストレージの割り当てと使用に関する制限事項を認識しておく必要があります。

最も重要なストレージの制限事項を以下に示します。詳細については、link:https://mysupport.netapp.com/matrix/["Interoperability Matrix Tool"^]も確認してください。


TIP: ONTAP Selectでは、ストレージの割り当てと使用に関連するいくつかの制限が適用されます。ONTAP Selectクラスタを導入する前、またはライセンスを購入する前に、これらの制限事項を理解しておく必要があります。詳細については、link:concept_lic_evaluation.html["ライセンス"]セクションを参照してください。



=== 物理ストレージ容量を計算する

ONTAP Selectストレージ容量は、ONTAP Select仮想マシンに接続された仮想データディスクとルートディスクの合計許容サイズに対応します。容量を割り当てる際には、この点を考慮する必要があります。



=== シングルノード クラスタの最小ストレージ容量

シングルノード クラスタ内のノードに割り当てられるストレージ プールの最小サイズは：

* 評価：500 GB
* 本番環境：1.0 TB


本番環境への導入に必要な最小割り当て容量は、ユーザーデータ用に1TB、さらにさまざまなONTAP Select内部プロセスで使用される約266GB（必要なオーバーヘッドとみなされます）です。



=== マルチノードクラスタの最小ストレージ容量

マルチノード クラスタの各ノードに割り当てられるストレージプールの最小サイズは次のとおりです：

* 評価：1.9 TB
* 本番環境：2.0 TB


本番環境への導入に必要な最小割り当て容量は、ユーザーデータ用に2TB、さらにONTAP Selectの各種内部プロセスで使用される約266GBで、これは必要なオーバーヘッドとみなされます。

[NOTE]
====
HAペアを構成する各ノードは、同じストレージ容量を備えている必要があります。

HAペアに必要なストレージ容量を見積もる際には、すべてのアグリゲート（ルートとデータ）がミラーリングされることを考慮する必要があります。その結果、アグリゲート内の各プレックスは同量のストレージを消費します。

たとえば、2TBのアグリゲートが作成されると、2つのplexインスタンスに2TB（plex0に2TB、plex1に2TB）が割り当てられ、ライセンスされたストレージの合計容量4TBが使用されます。

====


=== ストレージ容量と複数のストレージプール

ローカルの直接接続ストレージ、VMware vSAN、または外部ストレージアレイを使用する場合、各ONTAP Selectノードで最大400TBのストレージを使用するように設定できます。ただし、直接接続ストレージまたは外部ストレージアレイを使用する場合、単一のストレージプールの最大サイズは64TBです。したがって、このような状況で64TBを超えるストレージを使用する予定がある場合は、以下のように複数のストレージプールを割り当てる必要があります：

* クラスタ作成プロセス中に初期ストレージプールを割り当てる
* 1つ以上の追加ストレージプールを割り当てることで、ノードのストレージ容量を増やします



NOTE: 各ストレージプールには2%のバッファが未使用のまま残されるため、容量ライセンスは必要ありません。ONTAP Selectは、容量上限を指定しない限り、このストレージを使用しません。容量上限を指定すると、指定された量が2%のバッファゾーン内に入らない限り、ONTAP Selectはその量のストレージを使用します。バッファは、ストレージプール内のすべてのスペースを割り当てようとしたときに時々発生するエラーを防ぐために必要です。



=== ストレージ容量と VMware vSphere

VMware vSANを使用する場合、データストアのサイズは64TBを超えることができます。ただし、ONTAP Selectクラスタの作成時に最初に割り当てることができるのは最大64TBまでです。クラスタが作成された後、既存のvSANデータストアから追加のストレージを割り当てることができます。ONTAP Selectで消費可能なvSANデータストア容量は、VMストレージポリシーセットに基づいています。



=== ベストプラクティス

ハイパーバイザーコアハードウェアに関する以下の推奨事項を検討してください：

* 単一のONTAP Select アグリゲート内のすべてのドライブは、同じタイプである必要があります。たとえば、同じアグリゲート内でHDDドライブとSSDドライブを混在させないでください。




== プラットフォームライセンスに基づく追加のディスクドライブ要件

選択できるドライブは、プラットフォームのライセンス提供内容によって制限されます。


NOTE: ディスクドライブの要件は、ローカルRAIDコントローラとドライブを使用する場合、およびソフトウェアRAIDを使用する場合に適用されます。これらの要件は、ONTAP Select vNASソリューションを介してアクセスされる外部ストレージには適用されません。

.Standard
* 8～60台の内蔵HDD（NL-SAS、SATA、10K SAS）


.Premium
* 8～60台の内蔵HDD（NL-SAS、SATA、10K SAS）
* 4～60個の内蔵SSD


.プレミアムXL
* 8～60台の内蔵HDD（NL-SAS、SATA、10K SAS）
* 4～60個の内蔵SSD
* 4～14個の内部NVMe



NOTE: ローカルDASドライブを使用したソフトウェアRAIDは、プレミアムライセンス（SSDのみ）およびプレミアムXLライセンス（SSDまたはNVMe）でサポートされています。



== ソフトウェアRAIDを使用したNVMeドライブ

ソフトウェアRAIDを設定してNVMe SSDドライブを使用するようにすることができます。ご使用の環境は、以下の要件を満たしている必要があります：

* サポートされているDeploy管理ユーティリティを使用したONTAP Select
* Premium XLプラットフォームライセンス製品または90日間の評価ライセンス
* VMware ESXi バージョン 8.0 以降
* 仕様1.0以降に準拠したNVMeデバイス


NVMeドライブを使用する前に、手動で設定する必要があります。詳細については、link:task_chk_nvme_configure.html["ホストがNVMeドライブを使用するように設定する"]を参照してください。
