---
sidebar: sidebar 
permalink: reference_plan_ots_general.html 
keywords: plan, planning, general requirements 
summary: ONTAP Select 導入の計画の一環として考慮すべき一般的な要件がいくつかあります。 
---
= ONTAP Select の要件と計画上の考慮事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 環境の導入を計画する際には、いくつかの一般的な要件を考慮する必要があります。



== KVMに必要なLinuxの知識とスキル

KVMハイパーバイザーを使用したLinuxは、複雑な作業環境です。KVM上にONTAP Selectを導入する前に、必要な知識とスキルを習得しておく必要があります。

Linuxサーバーディストリビューション:: ONTAP Select 導入に使用する特定の Linux ディストリビューションに関する経験が必要です。具体的には、以下のタスクを実行できる必要があります：
+
--
* Linuxディストリビューションをインストールします
* CLIを使用してシステムを設定する
* ソフトウェアパッケージと依存関係を追加します


--


Linuxサーバーの準備に関する詳細情報（必要な構成やソフトウェアパッケージを含む）については、link:kvm-host-configuration-and-preparation-checklist.html["ホスト構成チェックリスト"]を参照してください。現在サポートされているLinuxディストリビューションについては、ハイパーバイザーの要件を参照してください。

KVMの導入と管理:: 仮想化の一般的な概念を理解しておく必要があります。さらに、KVM環境でONTAP Selectをインストールおよび管理する際に使用する必要があるLinux CLIコマンドがいくつかあります：
+
--
* `virt-install`
* `virsh`
* `lsblk`
* `lvs`
* `vgs`
* `pvs`


--
ネットワーキングと Open vSwitch の設定:: ネットワークの概念とネットワークスイッチの設定について理解しておく必要があります。さらに、Open vSwitchに関する経験も必要です。KVM環境でONTAP Selectネットワークを設定する際には、次のネットワークコマンドを使用する必要があります：
+
--
* `ovs-vsctl`
* `ip`
* `ip link`
* `systemctl`


--




== クラスタサイズと関連する考慮事項

クラスタサイズに関連して考慮すべき計画上の問題がいくつかあります。

クラスター内のノード数:: ONTAP Selectクラスタは、1、2、4、6、8、10、または12個のノードで構成されます。アプリケーションの要件に基づいて、クラスタのサイズを決定する必要があります。たとえば、エンタープライズ環境での導入においてHA機能が必要な場合は、マルチノードクラスタを使用する必要があります。
専用型と併設型:: アプリケーションのタイプに基づいて、専用モデルまたはコロケーションモデルのどちらの導入方式に従うかを判断する必要があります。コロケーションモデルは、ワークロードの多様性とより緊密な統合により、より複雑になる可能性があることに注意してください。




== ハイパーバイザーホストに関する考慮事項

ハイパーバイザーホストに関連して検討すべき計画上の問題がいくつかあります。


CAUTION: NetApp サポートから指示がない限り、ONTAP Select 仮想マシンの構成を直接変更しないでください。仮想マシンは、Deploy 管理ユーティリティを通じてのみ構成および変更する必要があります。NetApp サポートの支援なしに Deploy ユーティリティの外部で ONTAP Select 仮想マシンを変更すると、仮想マシンに障害が発生し、使用できなくなる可能性があります。

ハイパーバイザーに依存しない:: ONTAP SelectとONTAP Select Deploy管理ユーティリティは、どちらもハイパーバイザーに依存しません。以下のハイパーバイザーは、どちらのシステムでもサポートされています。
+
--
* VMware ESXi
* カーネルベース仮想マシン（KVM）


--



NOTE: ONTAP Select 9.14.1以降、KVMハイパーバイザーのサポートが復活しました。以前は、KVMハイパーバイザー上に新しいクラスタを導入するためのサポートがONTAP Select 9.10.1で削除され、既存のKVMクラスタとホストの管理（オフラインにする、または削除する場合を除く）のサポートがONTAP Select 9.11.1で削除されました。

サポートされているプラットフォームに関する追加の詳細については、ハイパーバイザー固有の計画情報およびlink:reference_release_notes.html["リリース ノート"]を参照してください。

ONTAP Selectノードおよび管理ユーティリティ用のハイパーバイザー:: Deploy管理ユーティリティとONTAP Selectノードは、どちらも仮想マシンとして実行されます。Deployユーティリティ用に選択するハイパーバイザーは、ONTAP Selectノード用に選択するハイパーバイザーとは独立しています。この2つを組み合わせる際には、完全な柔軟性があります：
+
--
* VMware ESXi 上で動作するデプロイユーティリティは、VMware ESXi または KVM 上の ONTAP Select クラスタを作成および管理できます
* KVM上で動作するデプロイユーティリティは、VMware ESXiまたはKVM上のONTAP Selectクラスタを作成および管理できます


--
ホストあたり 1 つ以上の ONTAP Select ノード インスタンス:: 各ONTAP Selectノードは専用の仮想マシンとして実行されます。同じハイパーバイザーホストに複数のノードを作成できますが、次の制限があります：
+
--
* 単一の ONTAP Select クラスタの複数のノードを同じホスト上で実行することはできません。特定のホスト上のすべてのノードは、異なる ONTAP Select クラスタのノードである必要があります。
* 外部ストレージを使用する必要があります。
* ソフトウェアRAIDを使用する場合、ホスト上に展開できるONTAP Selectノードは1つだけです。


--
クラスタ内のノード間のハイパーバイザの整合性:: ONTAP Select クラスタ内のすべてのホストは、同じバージョンおよびリリースのハイパーバイザー ソフトウェアで実行する必要があります。
各ホスト上の物理ポート数:: 各ホストは、1つ、2つ、または4つの物理ポートを使用するように構成する必要があります。ネットワークポートの設定にはある程度の柔軟性がありますが、可能な限り以下の推奨事項に従ってください：
+
--
* シングルノード クラスタのホストには、物理ポートが2つ必要です。
* マルチノードクラスタ内の各ホストには、4つの物理ポートが必要です


--
ONTAP SelectとONTAPハードウェアベースクラスタの統合:: ONTAP Select ノードを ONTAP ハードウェアベースクラスタに直接追加することはできません。ただし、オプションで ONTAP Select クラスタとハードウェアベースの ONTAP クラスタの間にクラスタピアリング関係を確立することもできます。




== ストレージに関する考慮事項

考慮すべきホストストレージに関連する計画上の問題がいくつかあります。

RAIDタイプ:: ESXiで直接接続ストレージ（DAS）を使用する場合、ローカルハードウェアRAIDコントローラまたはONTAP Selectに付属のソフトウェアRAID機能を使用するかどうかを決定する必要があります。ソフトウェアRAIDを使用する場合は、link:reference_plan_ots_storage.html["ストレージとRAIDに関する考慮事項"]詳細については、こちらをご覧ください。
ローカルストレージ:: RAIDコントローラで管理されるローカルストレージを使用する場合は、以下を決定する必要があります：
+
--
* 1つまたは複数のRAIDグループを使用するかどうか
* 1つまたは複数のLUNを使用するかどうか


--
外部ストレージ:: ONTAP Select vNASソリューションを使用する際は、リモートデータストアの配置場所とアクセス方法を決定する必要があります。ONTAP Select vNASは以下の構成をサポートしています：
+
--
* VMware vSAN
* 汎用外部ストレージアレイ


--
必要なストレージの見積もり:: ONTAP Selectノードに必要なストレージ容量を判断する必要があります。この情報は、ストレージ容量付きの購入済みライセンスを取得する際に必要となります。詳細については、ストレージ容量制限を参照してください。



NOTE: ONTAP Selectのストレージ容量は、ONTAP Select仮想マシンに接続されたデータディスクの合計許容サイズに対応します。

本番環境への導入のライセンス モデル:: 本番環境に導入する各ONTAP Selectクラスタには、容量階層または容量プールのライセンス モデルを選択する必要があります。詳細については、_ライセンス_のセクションを参照してください。




== 認証情報ストアを使用した認証

ONTAP Select Deploy クレデンシャルストアは、アカウント情報を保持するデータベースです。Deploy は、クラスタの作成と管理の一環として、アカウントクレデンシャルを使用してホスト認証を実行します。ONTAP Select 環境の導入を計画する際には、クレデンシャルストアがどのように使用されるかを理解しておく必要があります。


NOTE: アカウント情報は、Advanced Encryption Standard（AES）暗号化アルゴリズムとSHA-256ハッシュアルゴリズムを使用して、データベースに安全に保管されます。

クレデンシャルのタイプ:: 以下の種類のクレデンシャルがサポートされています：
+
--
* ホスト
+
*ホスト*クレデンシャルは、ONTAP SelectノードをESXiまたはKVMに直接導入する際に、ハイパーバイザーホストを認証するために使用されます。

* vcenter
+
*vcenter* クレデンシャルは、ホストがVMware vCenterで管理されている場合に、ONTAP SelectノードをESXiに導入する際にvCenterサーバーを認証するために使用されます。



--
アクセス:: 資格情報ストアは、Deploy を使用して通常の管理タスク（ハイパーバイザーホストの追加など）を実行する際に内部的にアクセスされます。認証情報ストアは、Deploy の Web ユーザーインターフェースおよび CLI から直接管理することもできます。


.関連情報
* link:reference_plan_ots_storage.html["ストレージとRAIDに関する考慮事項"]

