---
sidebar: sidebar 
permalink: reference_plan_ots_two_node.html 
keywords: plan, planning, two nodes, two node clusters 
summary: HAを使用した2ノードクラスタの導入には、他のクラスタノード構成で使用されるものと同じ計画と構成が必要です。ただし、2ノードクラスタを作成する際に注意すべきいくつかの違いがあります。 
---
= HAを備えたONTAP Select 2ノードクラスタ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
HAを使用した2ノードクラスタの導入には、他のクラスタノード構成で使用されるものと同じ計画と構成が必要です。ただし、2ノードクラスタを作成する際に注意すべきいくつかの違いがあります。

.ターゲット環境
2ノードクラスタは1組のHAペアで構成され、リモートオフィスや支店への導入向けに特別に設計されています。


NOTE: 主にリモートオフィスや支店環境向けに設計されていますが、必要に応じて2ノードクラスタをデータセンターに導入することもできます。

.ライセンス
VMware vSphereライセンスを使用して2ノードクラスタを導入できます。ただし、VMware ROBO StandardおよびAdvancedライセンスは、リモートオフィスや支店への導入に最適です。

.メディエーターサービス
クラスタが2つのノードで構成されている場合、ノードで障害が発生したり通信が失われたりすると、必要なクォーラムを達成できません。このようなスプリットブレイン状況を解決するために、ONTAP Select Deployユーティリティのすべてのインスタンスにメディエーターサービスが含まれています。このサービスは、アクティブな2ノードクラスタ内の各ノードに接続してHAペアを監視し、障害の管理を支援します。メディエーターサービスは、各2ノードクラスタに関連付けられた専用のiSCSIターゲットでHA状態情報を保持します。


CAUTION: アクティブな2ノードクラスタが1つ以上ある場合、クラスタを管理するONTAP Select Deploy仮想マシンは、常に稼働している必要があります。ONTAP Select Deploy仮想マシンが停止または失敗した場合、メディエーターサービスが利用できなくなり、2ノードクラスタのHA機能が失われます。

.クラスタとメディエーターサービスの場所
2ノードクラスタは通常、リモートオフィスまたはブランチオフィスに導入されるため、企業のデータセンターや管理サポートを提供するONTAP Select Deployユーティリティから離れた場所に配置できます。この構成では、ONTAP Select Deployユーティリティとクラスタ間の管理トラフィックはWAN経由で流れます。制限事項と制約事項の詳細については、link:reference_release_notes.html["リリース ノート"]を参照してください。

.Deploy構成データをバックアップする
クラスタの作成後を含め、定期的にlink:task_cli_clusters.html["ONTAP Select Deploy構成データをバックアップする"]することがベストプラクティスです。これは、バックアップにメディエーター構成データが含まれるため、2ノードクラスタでは特に重要になります。

.Deployに割り当てられた静的IPアドレス
ONTAP Select Deploy管理ユーティリティに静的IPアドレスを割り当てる必要があります。この要件は、1つ以上のONTAP Select 2ノードクラスタを管理するすべてのONTAP Select Deployインスタンスに適用されます。
