---
sidebar: sidebar 
permalink: reference_plan_dep_vmware.html 
keywords: plan, planning, ontap select deploy, vmware requirements 
summary: VMware 環境に ONTAP Select Deploy ユーティリティをインストールする前に考慮すべき、VMware 環境に固有のいくつかの要件と制限があります。 
---
= ONTAP Select Deployハイパーバイザーホストに関する考慮事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ハイパーバイザーホストに関連して検討すべき計画上の問題がいくつかあります。


CAUTION: NetApp サポートから指示がない限り、ONTAP Select 仮想マシンの構成を直接変更しないでください。仮想マシンは、Deploy 管理ユーティリティを通じてのみ構成および変更する必要があります。NetApp サポートの支援なしに Deploy ユーティリティの外部で ONTAP Select 仮想マシンを変更すると、仮想マシンに障害が発生し、使用できなくなる可能性があります。



== ハイパーバイザーに依存しない

ONTAP SelectとONTAP Select Deploy管理ユーティリティは、どちらもハイパーバイザーに依存しません。

ONTAP SelectとONTAP Select Deploy管理の両方で、以下のハイパーバイザーがサポートされています：

* VMware ESXi
* カーネルベース仮想マシン（KVM）



NOTE: サポートされているプラットフォームに関する追加の詳細については、ハイパーバイザー固有の計画情報およびlink:reference_release_notes.html["リリース ノート"]を参照してください。

.ONTAP Selectノードおよび管理ユーティリティ用のハイパーバイザー
Deploy管理ユーティリティとONTAP Selectノードは、どちらも仮想マシンとして実行されます。Deployユーティリティに選択するハイパーバイザーは、ONTAP Selectノードに選択するハイパーバイザーとは独立しています。この2つを組み合わせる際には、完全な柔軟性があります：

* VMware ESXi 上で動作するデプロイユーティリティは、VMware ESXi または KVM 上の ONTAP Select クラスタを作成および管理できます
* KVM上で動作するデプロイユーティリティは、VMware ESXiまたはKVM上のONTAP Selectクラスタを作成および管理できます


.ホストあたり 1 つ以上の ONTAP Select ノード インスタンス
各ONTAP Selectノードは専用の仮想マシンとして実行されます。同じハイパーバイザーホストに複数のノードを作成できますが、次の制限があります：

* 単一の ONTAP Select クラスタの複数のノードを同じホスト上で実行することはできません。特定のホスト上のすべてのノードは、異なる ONTAP Select クラスタのノードである必要があります。
* 外部ストレージを使用する必要があります。
* ソフトウェアRAIDを使用する場合、ホスト上に展開できるONTAP Selectノードは1つだけです。


.クラスタ内のノード間のハイパーバイザの整合性
ONTAP Select クラスタ内のすべてのホストは、同じバージョンおよびリリースのハイパーバイザー ソフトウェアで実行する必要があります。

.各ホスト上の物理ポート数
各ホストは、1つ、2つ、または4つの物理ポートを使用するように構成する必要があります。ネットワークポートの設定にはある程度の柔軟性がありますが、可能な限り以下の推奨事項に従ってください：

* シングルノード クラスタのホストには、物理ポートが2つ必要です。
* マルチノードクラスタ内の各ホストには、4つの物理ポートが必要です


.ONTAP Select を ONTAP ハードウェアベースクラスタと統合する
ONTAP Select ノードを ONTAP ハードウェアベースクラスタに直接追加することはできません。ただし、オプションで ONTAP Select クラスタとハードウェアベースの ONTAP クラスタの間にクラスタピアリング関係を確立することもできます。



== VMware ハイパーバイザー環境

VMware 環境に ONTAP Select Deploy ユーティリティをインストールする前に考慮すべき、VMware 環境に固有のいくつかの要件と制限があります。

.ESXiホストサーバのハードウェア要件
ESXiハイパーバイザーホストが満たす必要のある最小リソース要件がいくつかあります。ONTAP Selectを導入するホストが次の基本要件を満たしていることを確認してください：

* ESXiサーバー：
+
** ハードウェアとソフトウェアは64ビットである必要があります
** ONTAP Select ノードに定義されているサポート対象バージョンと同じバージョンに従う必要があります


* 仮想CPU（2）
* 仮想メモリ（4 GB）
* ストレージ（40 GB）
* DHCPが有効（静的IPアドレスの割り当ても可能）


.ネットワーク接続
ONTAP Select Deploy仮想マシンのネットワークインターフェイスが設定されており、単一の管理IPアドレスが割り当てられていることを確認する必要があります。DHCPを使用してIPアドレスを動的に割り当てることも、静的IPアドレスを手動で設定することもできます。

デプロイの決定によっては、デプロイ VM は、管理する vCenter サーバ、ESXi ハイパーバイザーホスト、および ONTAP Select ノードに接続できる必要があります。必要なトラフィックを許可するようにファイアウォールを設定する必要があります。

Deploy は VMware VIX API を使用して、vCenter サーバおよび ESXi ホストと通信します。まず最初に、TCP ポート 443 で SOAP over SSL を使用して接続を確立します。その後、ポート 902 で SSL を使用して接続が開かれます。さらに、Deploy は PING コマンドを発行して、指定した IP アドレスに ESXi ホストが存在することを確認します。

Deployは、次のプロトコルを使用してONTAP Selectノードおよびクラスタ管理IPアドレスと通信できる必要があります。

* PING コマンド（ICMP）
* SSH（ポート22）
* SSL（ポート443）


.IPバージョン4のサポート
ONTAP Select DeployはIPバージョン4（IPv4）のみをサポートしています。IPバージョン6（IPv6）はサポートされていません。この制限は、ONTAP Selectに次のような影響を与えます：

* Deploy仮想マシンの管理LIFにIPv4アドレスを割り当てる必要があります。
* Deploy では、 ONTAP LIF で IPv6 を使用するように設定された ONTAP Select ノードを作成できません。




== ONTAP Select Deploy VMware vCenterサーバに関する考慮事項



=== ESA用のVMware vSphere権限

vCenter で vSAN Express Storage Architecture (ESA) を作成および管理するために必要な、vSphere コンテンツ ライブラリの特定の権限を以下に示します：

* ライブラリアイテムを追加
* ローカルライブラリを作成する
* ライブラリアイテムを削除する
* ローカルライブラリを削除
* ファイルをダウンロード
* ストレージを読み取る
* ファイルを更新
* ライブラリを更新
* ライブラリアイテムを更新する
* ローカルライブラリを更新する
* 設定を表示する

