---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: ONTAP Selectは、ほとんどのONTAP機能を完全にサポートしています。多くのONTAP機能は、クラスタをデプロイすると、各ノードに対して自動的にライセンスが付与されます。ただし、一部の機能には別途ライセンスが必要です。 
---
= ONTAP Select による ONTAP 機能のサポート
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Selectは、ほとんどのONTAP機能をサポートしています。クラスタを導入すると、多くのONTAP機能のライセンスが各ノードに対して自動的に付与されます。ただし、一部の機能には別途ライセンスが必要です。


NOTE: ハードウェア固有の依存関係を持つONTAP機能は、一般的にONTAP Selectではサポートされていません。



== デフォルトで自動的に有効になるONTAP機能

次のONTAP機能はONTAP Selectでサポートされており、デフォルトでライセンスが付与されます：

* 自律型ランサムウェア対策（ARP）（手動更新）
* CIFS
* 重複排除と圧縮
* FlexCache
+
ONTAP Selectは、ライトバック機能付きFlexCacheキャッシュボリュームをサポートしています。ライトバック機能を持つFlexCacheオリジンボリュームはサポートされていません。

+
link:concept_ots_overview.html#flexcache-write-back-with-ontap-select["ONTAP SelectでのFlexCacheライトバックの詳細"]

* FlexClone
* iSCSI
* NDMP
* NetApp Volume Encryption（制限対象外の国のみ）
* NFS
* NVMe over TCP
* ONTAPマルチテナンシー機能
* ONTAP S3
* S3 SnapMirror
* SnapLock Select
+
SnapLock SelectはONTAP Select向けに設計されたONTAP SnapLockの実装であり、SnapLock Enterpriseが含まれています。SnapLock Complianceは含まれていません。

+
link:https://docs.netapp.com/us-en/ontap/snaplock/index.html["ONTAP SnapLockについて学ぶ"^]

* SnapMirror
* SnapMirrorクラウド
* SnapRestore
* SnapVault
* Storage VM ディザスタリカバリ（SVM DR）
+
ONTAP SelectはSVM DRをソースと宛先の両方としてサポートし、最大16件の関係を設定できます。SVM DRのサポートは、ソースONTAPバージョンからバージョン+2までの使用に限定されます。たとえば、ONTAP Select 9.12.1ソースは、宛先ONTAPバージョン9.12.1、9.13.1、または9.14.1に接続できます。





== 別途ライセンスが必要な ONTAP 機能

デフォルトでは有効になっていないONTAP機能については、それぞれに別途ライセンスを取得する必要があります。次のような機能が含まれます：

* FabricPool
+

NOTE: StorageGRID を使用する場合、FabricPool ライセンスは必要ありません。

* MetroCluster SDS（ONTAP Select プレミアムライセンスの提供）


.関連情報
* link:concept_ots_overview.html#compare-ontap-select-and-ontap-9["ONTAP SelectとONTAP 9の比較"]
* link:https://mysupport.netapp.com/site/systems/master-license-keys["NetApp ONTAP マスターライセンスキーについて学ぶ"^]

