---
sidebar: sidebar 
permalink: task_adm_resize.html 
keywords: administer, administering, web, resizing nodes, resizing 
summary: ONTAP Selectクラスタを導入した後、Deploy管理ユーティリティを使用してノードのハイパーバイザーインスタンスタイプをアップグレードできます。 
---
= ONTAP Select クラスタノードのサイズを変更する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Selectクラスタを導入した後、Deploy管理ユーティリティを使用してノードのハイパーバイザーインスタンスタイプをアップグレードできます。


NOTE: Capacity Tiersライセンス モデルおよびCapacity Poolsライセンス モデルを使用している場合、クラスタノードのサイズ変更操作を実行できます。


NOTE: 大規模インスタンスタイプへのサイズ変更は、ESXi でのみサポートされています。

.開始する前に
クラスターはオンライン状態である必要があります。

.タスク概要
このタスクでは、Deploy の Web ユーザー インターフェイスの使用方法について説明します。インスタンスのサイズ変更は、Deploy CLI を使用して実行することもできます。どのインターフェイスを使用する場合でも、サイズ変更操作に必要な時間はいくつかの要因によって大きく異なり、完了までにかなりの時間を要する場合があります。ノードのサイズは、より大きなサイズにのみ変更できます。

.手順
. 管理者アカウントを使用して、DeployユーティリティのWebユーザーインターフェースにSign inします。
. ページ上部の*Cluster*タブをクリックし、リストから目的のクラスターを選択してください。
. クラスターの詳細ページで、ページ右側の歯車アイコンをクリックし、*Instance Resize*を選択します。
. *インスタンス タイプ*を選択し、ONTAP クレデンシャルを入力して、*変更*をクリックします。


.終了後の操作
サイズ変更処理が完了するまで待つ必要があります。
