---
sidebar: sidebar 
permalink: task_adm_connectivity.html 
keywords: administer, administering, web, connectivity, network connectivity, network checker 
summary: 内部クラスタネットワーク上の2つ以上のONTAP Selectノード間のネットワーク接続をテストできます。通常、このテストはマルチノードクラスタを導入する前に実行し、処理が失敗する原因となる可能性のある問題を検出します。 
---
= ONTAP Selectノード間の接続を確認
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
内部クラスタネットワーク上の2つ以上のONTAP Selectノード間のネットワーク接続をテストできます。通常、このテストはマルチノードクラスタを導入する前に実行し、処理が失敗する原因となる可能性のある問題を検出します。

.開始する前に
テストに含まれるすべてのONTAP Selectノードは、設定が完了し、電源が投入されている必要があります。

.タスク概要
テストを開始するたびに、バックグラウンドで新しいプロセス実行が作成され、一意の実行識別子が割り当てられます。同時にアクティブにできるのは1つの実行のみです。

このテストには、動作を制御する2つのモードがあります：

* クイックこのモードは、基本的な無停止テストを実行します。PINGテストが実行され、ネットワークMTUサイズとvSwitchのテストも実行されます。
* 拡張モードでは、すべての冗長ネットワークパスに対してより包括的なテストが実行されます。アクティブなONTAP Selectクラスタでこれを実行すると、クラスタのパフォーマンスに影響が出る可能性があります。



NOTE: マルチノードクラスタを作成する前に、必ずクイックテストを実施することをお勧めします。クイックテストが正常に完了した後、必要に応じて、本番環境の要件に基づいた拡張テストを実行できます。

.手順
. 管理者アカウントを使用して、DeployユーティリティのWebユーザーインターフェースにSign inします。
. ページ上部の*Administration*タブをクリックし、*Network Checker*をクリックします。
. *Start New Run* をクリックし、HAペアのホストとネットワークを選択します
+
必要に応じて、追加のHAペアを追加および設定できます。

. *Start* をクリックして、ネットワーク接続テストを開始します。

