---
sidebar: sidebar 
permalink: task_cli_connectivity.html 
keywords: administer, administering, cli, connectivity, network connectivity, network checker 
summary: 内部クラスタネットワーク上の2つ以上のONTAP Selectノード間のネットワーク接続をテストできます。通常、このテストはマルチノードクラスタを導入する前に実行し、処理が失敗する原因となる可能性のある問題を検出します。 
---
= ONTAP Selectノード間のネットワーク接続を確認
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
内部クラスタネットワーク上の2つ以上のONTAP Selectノード間のネットワーク接続をテストできます。通常、このテストはマルチノードクラスタを導入する前に実行し、処理が失敗する原因となる可能性のある問題を検出します。

.開始する前に
テストに含まれるすべてのONTAP Selectノードは、設定が完了し、電源が投入されている必要があります。

.タスク概要
テストを開始するたびに、バックグラウンドで新しいプロセス実行が作成され、一意の実行識別子が割り当てられます。同時にアクティブにできるのは1つの実行のみです。

このテストには、動作を制御する2つのモードがあります：

* クイックこのモードは、基本的な無停止テストを実行します。PINGテストが実行され、ネットワークMTUサイズとvSwitchのテストも実行されます。
* 拡張モードでは、すべての冗長ネットワークパスに対してより包括的なテストが実行されます。アクティブなONTAP Selectクラスタでこれを実行すると、クラスタのパフォーマンスに影響が出る可能性があります。



NOTE: マルチノードクラスタを作成する前に、必ずクイックテストを実施することをお勧めします。クイックテストが正常に完了した後、必要に応じて、本番環境の要件に基づいた拡張テストを実行できます。

.手順
. 管理者アカウントを使用して、DeployユーティリティのCLIにSign inします。
. ネットワーク接続チェッカーの現在の実行状況を表示し、アクティブな実行がないことを確認します：
+
`network connectivity-check show`

. ネットワーク接続チェッカーを起動し、コマンド出力に表示される実行識別子をメモしてください：
+
`network connectivity-check start -host-names HOSTNAMES -vswitch-type VSWITCH_TYPE-mode MODE`

+
例

+
[listing]
----
network connectivity-check start -host-names 10.234.81.14
10.234.81.15 -vswitch-type StandardVSwitch -mode quick
----
. 実行識別子に基づいて、ネットワーク接続チェッカーの進行状況を監視します：
+
`network connectivity-check show -run-id RUN_ID`



.終了後の操作
ネットワーク接続チェッカーは通常、ONTAP-Internalポートグループに追加された一時的なポートとIPアドレスを削除することでクリーンアップを行います。ただし、接続チェッカーが一時ポートを削除できない場合は、オプション `-mode cleanup`を指定してCLIコマンドを再実行し、手動でクリーンアップ操作を実行する必要があります。ONTAP-Internalポートグループから一時ポートを削除しない場合、ONTAP Select仮想マシンが正常に作成されない可能性があります。
